### ISSUE TITLE
Inventory: Vertebral Column

### ISSUE THREAD

**Issue by JessHotaling** [RDFBones/RDFBonesPhaleron#1]
**Is your feature request related to a problem? Please describe.**
1. The section to add lumbar fragments is located after/below the sacrum.
2. There is no section for sacrum fragments.
3. There is no section for coccygeal units. 

**Describe the solution you'd like**
1. Is it possible to move the "Lumbar Vertebrae, Grouped" section to be placed after "L5" and before "Sacrum"? 
2. Can we please add a "Sacrum, Grouped" section that comes after "Sacrum" where we can enter number of fragments? "Number of unsided fragments" would be great if possible.  
3. Can a section be added after "Sacrum, Grouped" for "Number of Coccygeal Units"? 

**Additional context**
This screenshot shows where we would like the lumbar fragments to go. Thank you!
![image](https://user-images.githubusercontent.com/90312691/132485428-a7d5e4ab-d336-4895-964d-4e757e54efa7.jpeg)

**Comment by cuboideum** [comment]
Congratulations for winning first issue!

**Comment by zarquon42b** [comment]
Fixed first part of moving LV grouped up.

~~> Is it possible to move the "Lumbar Vertebrae, Grouped" section to be placed after "L5" and before "Sacrum"?~~

@cuboideum : 

> 2. Can we please add a "Sacrum, Grouped" section that comes after "Sacrum" where we can enter number of fragments? "Number of unsided fragments" would be great if possible.
> 3. Can a section be added after "Sacrum, Grouped" for "Number of Coccygeal Units"?

Is this already implemented in the ontology?

**Comment by cuboideum** [comment]
> 2. Can we please add a "Sacrum, Grouped" section that comes after "Sacrum" where we can enter number of fragments? "Number of unsided fragments" would be great if possible.

Yes, this already exists in the ontology:
><owl:Class rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/AdultVertebralColumn">

[...]

>        <rdfs:subClassOf>
>            <owl:Restriction>
>                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000051"/>
>                <owl:someValuesFrom>
>                    <owl:Class>
>                        <owl:intersectionOf rdf:parseType="Collection">
>                            <rdf:Description rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/NumberOfUnclassifiedFragments"/>
>                            <owl:Restriction>
>                                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000136"/>
>                                <owl:qualifiedCardinality rdf:datatype="http://www.w3.org/2001/XMLSchema#nonNegativeInteger">1</owl:qualifiedCardinality>
>                                <owl:onClass rdf:resource="http://w3id.org/rdfbones/core#EntireSetOfSacralVertebrae"/>
>                            </owl:Restriction>
>                        </owl:intersectionOf>
>                    </owl:Class>
>                </owl:someValuesFrom>
>            </owl:Restriction>
>        </rdfs:subClassOf>

**Comment by zarquon42b** [comment]
Fixed 2/3
> ~~1. Is it possible to move the "Lumbar Vertebrae, Grouped" section to be placed after "L5" and before "Sacrum"?~~
> ~~2. Can we please add a "Sacrum, Grouped" section that comes after "Sacrum" where we can enter number of fragments? "Number of unsided fragments" would be great if possible.~~

One left:
> 3. Can a section be added after "Sacrum, Grouped" for "Number of Coccygeal Units"?
Do we have an ontological representation here?

**Comment by cuboideum** [comment]
> 3. Can a section be added after "Sacrum, Grouped" for "Number of Coccygeal Units"?
Do we have an ontological representation here?

I have set up issue RDFBones/Phaleron-SkeletalInventory#15 and pull request RDFBones/Phaleron-SkeletalInventory#16. Now I am waiting for @15E601 to review.

**Comment by cuboideum** [comment]
In terms of ontology, everything is set. 'Number of coccygeal units' remains to be implemented with the AnthrogGraph app.

**Comment by 15E601** [comment]
Ontodia does not find 'EntireBoneOrgan_fma12527'
![ontodia](https://user-images.githubusercontent.com/67172847/136188895-5c400ef2-1882-411e-b382-8e91a8fec545.png)

The ontology uploaded to Metaphacts appears to be correct, where 'EntireBoneOrgan_fma12527' is under the 'AdultvertebralColumn' section
![owl](https://user-images.githubusercontent.com/67172847/136189063-ccce1355-fa7e-4cfe-bb68-7cf81b2171c8.png)

Why is it not showing up? Could this be an issue with the 'NumberOfPresentElements' class?

**Comment by 15E601** [comment]
NumberOfPresentElements bug fixed by recent commit in the Standards-SI
All requests of this issue now implemented
