### ISSUE TITLE
Associate observer and date of observation with record

### ISSUE THREAD

**Issue by JEB13** [RDFBones/RDFBonesPhaleron#10]
We have no way of knowing when record was entered or when.

Identification for individual and date of observation entered with record.

**Comment by cuboideum** [comment]
We discussed this on an AnthroGraph meeting on 14 September 2021. For skeletal inventory we just implement the resulting data set for which date and author are metadata. With the palaeopathology module we might consider processes to a larger extent, so the solution might be different. For now, I have assigned the 'skeletal inventory module' label to this issue.

**Comment by cuboideum** [comment]
Potentially, there are two persons involved in two processes towads the creation of the dataset, one who coded the skeleton and another who entered the data.

Would you like to enter both names and dates?

**Comment by JEB13** [comment]
Would like to enable recording all who touch record, but may have multiple people coding the bone.

Cheers!

Jane
________________________________

**Comment by cuboideum** [comment]
On which level of detail would you like to reference participants? For example, we could have 'participants' items for the inventory sections (i.e. the tabs in the data entry form).

**Comment by JEB13** [comment]
I don't think for sections. I think for inventories, for paleopathology, but important to who who touched the data collection/entry and when.

We could mention tomorrow, but that's my take.

Cheers!

Jane
________________________________

**Comment by cuboideum** [comment]
Data items taking participants can be configured to allow several people to be named. The most elegant solution would be to define a number of roles (e.g. 'coder', 'data editor') covering the necessary work steps. Entries then would contain the date of the contribution, the name of the contributor and her/his role in creating the dataset.

But I will have to discuss implementation of this with Stefan before coming up with a concrete solution.

**Comment by cuboideum** [comment]
Fixed with commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
