### ISSUE TITLE
Inventory left and right sides of frontal bone separately

### ISSUE THREAD

**Issue by JEB13** [RDFBones/RDFBonesPhaleron#11]
Pathology clearly needs to be recorded by side and the inventory is not consistent with this

Change Inventory to record right and left sides separately.

**Comment by 15E601** [comment]
I'm assuming this means areas with a clear left/right divide only, so cranium and vertebral column will stay as is, yes?
There are two options I see: Either we keep the elements side by side and add a save button for left and right, ex.:
![side](https://user-images.githubusercontent.com/67172847/133266375-e7e47858-3923-45db-a661-5cf470fd9baf.png)

Or we cycle through first the left, then all the right halves, ex:
![top](https://user-images.githubusercontent.com/67172847/133266486-dcf596eb-d927-44a1-97d5-f82f5a38412d.png)

Is this what you had in mind? The first option would keep the inventory mostly looking as it is, but you can enter one side first. The second would make the pages a lot longer, but you don't have to scroll up and down as much.

I also assume the unsided fragments always get done last, so I would put them together at the bottom as one group.

**Comment by 15E601** [comment]
I just noticed I missed the very clear reference to the cranium in the title. So clearly this split is meant for every element that has a divide between a left and right half - I assume the spinal column is **not** intended to be also split between left and right?

**Comment by JEB13** [comment]
This was merely in response to the request from Felix to reconcile our inventory with the paleopathology entry.

Jane


________________________________

**Comment by JEB13** [comment]
The neural arches for the vertebrae will be coded separately.

**Comment by 15E601** [comment]
Squamous part of Frontal Bone is now split into left and right.
