### ISSUE TITLE
Adding rare number anomalies for ribs and vertebrae

### ISSUE THREAD

**Issue by JEB13** [RDFBones/RDFBonesPhaleron#12]
We have no place to record the rare occurrence of thirteen ribs (r or l), a 13th thoracic vertebra, a sixth lumbar vertebra.

Please add these units to the inventory.

**Comment by 15E601** [comment]
All 3 were actually planned for and implemented in the ontology, but I failed to add them correctly when writing the app. They are now all available.

**Comment by JEB13** [comment]
Yay!  Just going down our list to make certain we are all on same page.

Jane
________________________________
