### ISSUE TITLE
Bone Addition Location

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#13]
**Is your feature request related to a problem? Please describe.**
We need to add an option for location of bone addition similar to location of bone loss. This does not mean the location on the bone (e.g., medial, distal third), but the aspect of the bone affected (e.g., periosteal bone, cortex).

**Describe the solution you'd like**
The options can be the same as bone loss:
![Screenshot (6)](https://user-images.githubusercontent.com/90314688/133412418-32c7e49f-c2d8-4c17-aeb1-f901623b430e.png)

**Additional context**
The option "other" can be used for facial bones etc., where the categories are more difficult to define.

**Comment by HannahLiedl** [comment]
We are also including this in our updated paleopathology templates. I assume this is less of something to add, but more information on what has changed.

**Comment by cuboideum** [comment]
If the categories are the same as for 'bone loss location', I would suggest to use the same measurement datum for both sections. This would create another general data item describing location of features. We need distinctive names to avoid confusion.

My suggestion:

* 'Within Bone Location' -> 'Aspect of Skeletal Element'
* 'Bone Loss Location' -> 'Location on Skeletal Element'

What do you think?

**Comment by HannahLiedl** [comment]
Yes, it should be the same for both lesion types. I do like "aspect" and "location" as terms.

I'll see if I can add Jane into this thread to get her opinion. I have not entirely figured out the system.

@JEB13

**Comment by cuboideum** [comment]
Well done, @JEB13 is the correct way to drag her in. Jane should have received an email about her being mentioned and this will hopefully make her check out this issue.

**Comment by cuboideum** [comment]
Fixed with commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
