### ISSUE TITLE
Bone Loss - Cranial Porosity

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#14]
**Is your feature request related to a problem? Please describe.**
We want to add a more specific option for cranial porosity under bone loss.

**Describe the solution you'd like**
We'd like to add the following to the section "bone loss". This is only necessary for the cranial palaeopathology:
![Screenshot (7)](https://user-images.githubusercontent.com/90314688/133418074-bafdb570-5524-4a92-968c-97b25dc03526.png)

**Additional context**
I also added this in the updated palaeopathology template and scoring key.

**Comment by cuboideum** [comment]
Fixed with commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
