### ISSUE TITLE
Change in shape/size: regions of interest

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#15]
**Is your feature request related to a problem? Please describe.**
As you pointed out, there was a need to define specific regions of interest for change in shape and size

**Describe the solution you'd like**
We propose the following regions for these changes:
![Screenshot (5)](https://user-images.githubusercontent.com/90314688/133453032-ed0c9675-6d12-4f37-a1ec-d49695d14ee4.png)

**Additional context**
Small skull: was present in initial draft but now deleted

I also changed this in the updated template and scoring key.

**Comment by cuboideum** [comment]
Fixed with issues #80, #81 and #84.
