### ISSUE TITLE
Tabs for palaeopathology main page

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#17]
The palaeopathology main page is structured according to areas of the skeleton. These are represented by tabs in the following mock-up.

![PhaleronMockups-PalaeopathologyMainPage](https://user-images.githubusercontent.com/8103073/133590411-3e80e231-ff29-4dbb-9c4b-9e4f24b4a55f.png)

The Phaleron Bioarchaeological Project needs to decide which areas make sense for them and in what sequence they should appear. @JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by JEB13** [comment]
It would be more logical in data collection to have upper limb hand lower limb foot.  One question arises is how much we want to offend the anatomists.  Arm + forearm = upper limb; thigh + leg = lower limb.  Cranium + mandible = skull, as I said before.  I don't always follow these myself, but I do know that Chris Dudar, for example, does. (I think).

**Comment by cuboideum** [comment]
I think the structure of the tabs (what is scored where) should totally reflect the way you work in practice. The naming should please the anatomist (and Chris) as much as possible.

**Comment by HannahLiedl** [comment]
I agree, upper limb - hand - lower limb - foot makes more sense from the recording view point. This follows more the recording flow.

**Comment by cuboideum** [comment]
We are now implementing the following tabs:

- General (People, Dates)
- Skull
- Vertebral Column
- Thorax
- OsCoxae
- Shoulder Girdle
- Upper Limb
- Lower Limb

@JEB13: Is this correct?

**Comment by cuboideum** [comment]
Fixed with commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
