### ISSUE TITLE
Implementation of optional data items in AnthroGraph

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#18]
The palaeopathology module contains conditions that are scored as present/not present. Additional data fields only apply if 'present' is selected. Examples for such conditions are 'Myositis Ossificans',  'Stellate Scars', 'Sequestrum' and 'Involucrum' in the following screenshot.

![PhaleronPatho-Mockup-AddAddedBoneObservationPage](https://user-images.githubusercontent.com/8103073/133591608-c2871526-9d8b-4e49-8988-636d267ce60d.png)

How should these be implemented in AnthroGraph to avoid erroneous data entries and unnecessary creation of triples while providing a good user experience?

**Comment by JEB13** [comment]
Yes, correct.  Go ahead.

**Comment by cuboideum** [comment]
The RDFBones/AnthroGraph workgroup has discussed this issue on 21 September 2021. We will first fathom the options offered by the Metaphactory framework. Then we will come up with practical solutions for the Phaleron project to choose from.

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/AnthroGraph/PBP-App/commit/57ee529e2a490a0d55db56703b72da1417859e95.
