### ISSUE TITLE
Documenting involvement of researchers in dataset creation

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#19]
Participants in research processes can be references with the date of their interaction and the role which they had in the process. An example for such an association is shown at the bottom of the following mock-up:

![PhaleronPatho-PalaopathologyMockup-AddAddedBoneObservationPage](https://user-images.githubusercontent.com/8103073/133591608-c2871526-9d8b-4e49-8988-636d267ce60d.png)

The Phaleron Bioarchaeological Project needs to decide at which levels participants should be documented within the palaeopathology module.  @JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by cuboideum** [comment]
This is not a duplicate of issue #10. The skeletal inventory module is implemented in a different way in AnthroGraph as it is the case with the palaeopathology module. Solutions, therefore, might be different.

**Comment by cuboideum** [comment]
Should there be comments boxes to record participants' contributions?

**Comment by JEB13** [comment]
Ah, yes.  OK Comments box, yes.  X-ray/CT documentation should be here, data input.  Sampling on inventory.

**Comment by cuboideum** [comment]
>  X-ray/CT documentation should be here, data input. Sampling on inventory.

I have opened separate issues for X-ray/CT documentation (#29) and material sampling (#28).

**Comment by JEB13** [comment]
Yes, settled?

**Comment by cuboideum** [comment]
Fixed with commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
