### ISSUE TITLE
Inventory: Additional Individuals

### ISSUE THREAD

**Issue by JessHotaling** [RDFBones/RDFBonesPhaleron#2]
**Is your feature request related to a problem? Please describe.**
There is currently no place to record the presence of additional individuals. 

**Describe the solution you'd like**
Can we please add a check box to the inventory for "More than one individual present"?

**Comment by 15E601** [comment]
I propose the following classes:

ID: phaleron-si:AdditionalIndividuals
Label: Additional individuals
Definition: A measurement datum assessing the presence of more than one individual in an inventory.
Value Specification: ('has value specification' only 'Additional individuals value specification')

ID: phaleron-si:AdditionalIndividualsValueSpecification
Label: Additional individuals value specification
Definition: A value specification that specifies the presence or non-presence of more than one individual in an inventory.
Parent Class: obo:OBI_0001930
Category Label: ('has category label' only 'Additional individuals label')

![Screenshot from 2021-09-12 18-38-56](https://user-images.githubusercontent.com/67172847/132996542-7cd37f70-4189-48a6-8835-c493a1faf9b2.png)

@cuboideum does this conform to your expectations?

**Comment by cuboideum** [comment]
So far, the Phaleron Bioarchaeological Project has implemented boolean (Yes/No) items as categorical items with two categories in their templates. Here, this is not explicitly the case. So we might consider implementing it as what it is, a boolean data item. This would save us the need to create categorical labels.

**Comment by cuboideum** [comment]
The name 'Additional Individuals' implies that there are remains from more than one additional individual present. I think a name like 'Additional Skeletal Material' might be better because it does not make assumptions about the qualities of the additional elements.

**Comment by 15E601** [comment]
As per our discussion, we will not use boolean items, but instead continue with the method for category labels we have had so far. I have renamed everything to fit the "additional skeletal material" concept.
I will leave the issue open until I have implemented the UI elements.

**Comment by 15E601** [comment]
Implemented. Can now be found under the Miscellaneous section.
