### ISSUE TITLE
Participant roles

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#20]
Participants in research processes can be references with the date of their interaction and the role which they had in the process. An example for such an association is shown at the bottom of the following mock-up:

![PhaleronPatho-PalaopathologyMockup-AddAddedBoneObservationPage](https://user-images.githubusercontent.com/8103073/133591608-c2871526-9d8b-4e49-8988-636d267ce60d.png)

The Phaleron Bioarchaeological Project needs to decide on a list of roles that researchers can have in various processes and that should be used throughout the application. The list should have as few entries as possible to avoid confusion of users but enough to record information at the required degree of detail.  @JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by JEB13** [comment]
I think the "recorder" and date will be the most significant data points.  Data entry, Sampling (with info in notes), X-ray/CT image taken are other aspects of skeleton treatment that could be recorded here.

**Comment by cuboideum** [comment]
In terms of roles, I would suggest to at least distinguish between people who have worked with the skeletal material and others who are exclusively working on the data set but have no immediate possibility to check back with the material. For example, this could be "recorder" as opposed to "editor".

**Comment by cuboideum** [comment]
>[...] Sampling (with info in notes), X-ray/CT image taken are other aspects of skeleton treatment that could be recorded here.

I have opened individual issues for these aspects:

* #28 on sampling
* #29 on imaging

**Comment by cuboideum** [comment]
> Data entry [...] are other aspects of skeleton treatment that could be recorded here.

Do you mean that there should be a clear distinction of when information was coded from the material and when the data was entered into the database? This could be specified by dedicated roles (cf. my [comment](https://github.com/RDFBones/RDFBonesPhaleron/issues/20#issuecomment-924659931) above).

Probably it would be good to also distinguish between data entry and later changes/corrections. Here, it might be useful to add a comment field to record what exactly was changed and why. But this is part of #19 and should be discussed there. This issue is just about the list of required roles.

**Comment by JEB13** [comment]
We discussed today: Observer _____(unlimited additions possible, with date); Data Entry ______(unlimited additions possible, with date).  See comments above concerning a brief sampling entry for inventory; x-ray/CT.  Images are taken at every stage, and this could be included, but right now inventorying the images would be a job in of itself.  We put all images in a given folder per skeleton on google drive.

**Comment by JEB13** [comment]
Settled?

**Comment by cuboideum** [comment]
Fixed with commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
