### ISSUE TITLE
Displayed information on palaeopathology sections

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#21]
In the palaeopathology main page, existing palaeopathology sections are presented in lists. In the following mock-up, these lists just contain the user-defined section labels.

![PhaleronPatho-Mockup-PalaeopathologyMainPage](https://user-images.githubusercontent.com/8103073/133593267-d4838b74-091e-4ab1-ba73-97b190229ae4.png)

Are there additional data items from the palaeopathology sections that should be displayed in the tables, along with the labels? @JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by JEB13** [comment]
This really covers the type of observations and organization.  Others?

**Comment by hayesleigh** [comment]
Another category would need to be added to this is we add the mixed bone
loss/addition category to the paleopathology template.

-Leigh

**Comment by JEB13** [comment]
We had a lengthy and meaningful discussion of "cortex perforated" and while this organization devolves from my original configuration created in '92 or '93, I am willing to say that other systems are more robust.  We came up with a "mixed" category, which more realistically represents the spicules, the involucrum, the sequestrum, the shell, and the cloaca categories.  We also think that cranial porosity actually fits here.  Hannah (and I) are working on this mixed category and reducing bone addition/bone subtraction a bit -- I'm sorry, but this will be MUCH better.

**Comment by JEB13** [comment]
Settled?

**Comment by cuboideum** [comment]
During a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 30 August 2022 it was decided to close the issue for now. If additional columns in tables should be beneficial, this will be requested in additional issues.
