### ISSUE TITLE
'Within Bone Location': Suggested change of name

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#22]
The Phaleron Paleopathology Scoring Key (Version 17 September 2021) defines the categorical data item 'Within Bone Location'. The description contains the following passage:

> This scoring key will be utilized to identify the aspect of the skeletal element that is impacted by the pathological lesion.

As 'skeletal element' is not clearly defined, here, it is not quite clear whether the specification made by the data item refers to the anatomical region of interest (possibly referred to as 'skeletal element') or the bone of which the region is a part. As anatomical regions of interest do not necessarily describe entire bone organs, this distinction would produce different locations.

For illustration, consider the following example. If the category '11-Distal' is applied to the anatomical region of interest 'L Humerus: P1/3' (i.e. the proximal third of the diaphysis of the left humerus), the specified location does not refer to the distal end of the left humerus as such. 

I assume that the data item is meant to refer to the anatomical region of interest and I also think it should be. The aspect of the relevant bone organ might already be defined by the anatomical region of interest itself, so scoring the aspect of the bone might create redundant information. Also, the categorical data item 'Extent of Involvement' explicitly refers to anatomical regions of interest and a consistent definition of data items helps to avoid confusion.

This understanding of the data item's definition is also the basis of the following mock-up for a palaeopathology data entry form:

![ObservationOfAddedBoneFormMockup](https://user-images.githubusercontent.com/8103073/133591608-c2871526-9d8b-4e49-8988-636d267ce60d.png)

The name of the data item should reflect its meaning in order to avoid misunderstanding. Assuming the interpretation given above being correct, I, therefore, propose a change of name. This might also consider the fact that the data item describes the aspect of skeletal elements rather than defining an exact location.

Based on these reflections, I propose to change the data item's name to 'Aspect of skeletal element'.

@JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by JEB13** [comment]
"Skeletal Element" is defined as a bone, e.g, humerus, 1st rib, parietal bone, etc.  Your system makes sense, as we re-organize types of observations within regions.

**Comment by HannahLiedl** [comment]
Yes, this makes sense and it is how I have always used it. The "within bone location" (or now "aspect") refers the the anatomical region of interest. If I record a lesion on the proximal third of the humerus diaphysis, the location would refer to this specific section of the humerus.

**Comment by JEB13** [comment]
Yes, that works for me!

Jane
________________________________

**Comment by JEB13** [comment]
We should discuss briefly Monday with whole group, in respect to aspect/within bone location.  I think we can resolve readily.

**Comment by cuboideum** [comment]
Fixed in commit https://github.com/RDFBones/Phaleron-Pathologies/commit/46cdf8661327e01750720922e653340898c73bb0.
