### ISSUE TITLE
'Presence of Pathological Lesion': Suggested change of name

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#24]
The Phaleron Paleopathology Scoring Key (Version 17 September 2021) defines the categorical data item 'Presence of Pathological Lesion'. The description contains the following passage:

> This scoring key will be used throughout the paleopathology spreadsheet to denote whether a particular feature of characteristic is present or absent.

The description is much broader than the title. I suggest to make the entire data item more versatile by just calling it 'Presence of Feature'. Then it could be reused in other modules. On the other hand, I do not think that an item limited to the presence of pathological lesions would bring any advantages.

What do you think? @JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by JEB13** [comment]
Your suggestions makes sense to me, but let me hear from others!

**Comment by JessHotaling** [comment]
> Your suggestions makes sense to me, but let me hear from others!

This makes sense to me as well! I think it's a good idea to make things as reusable as possible for other modules.

**Comment by JEB13** [comment]
Go ahead!

**Comment by cuboideum** [comment]
Fixed in commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
