### ISSUE TITLE
'Cortex Intact, Spicules': Suggested change of name

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#25]
The Phaleron Paleopathology Scoring Key (Version 17 September 2021) defines the categorical data item 'Cortex intact, spicules'. As a class name, this is not very expressive.

Would it be possible to choose a more characteristic name, e.g. 'Bone Spicules'?

@JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by JEB13** [comment]
Fine with me!!

**Comment by JEB13** [comment]
Go Ahead!!  :-)

**Comment by cuboideum** [comment]
I have changed the title of the measurement datum title from 'Cortex intact, spicules' to 'Bone Spicules' in the ROBOT template for category labels. It will be implemented with the first RDF version of the ontology extension.

**Comment by JEB13** [comment]
We had a lengthy and meaningful discussion of "cortex perforated" and while this organization devolves from my original configuration created in '92 or '93, I am willing to say that other systems are more robust.  We came up with a "mixed" category, which more realistically represents the spicules, the involucrum, the sequestrum, the shell, and the cloaca categories.  We also think that cranial porosity actually fits here.  Hannah (and I) are working on this mixed category and reducing bone addition/bone subtraction a bit -- I'm sorry, but this will be MUCH better.

**Comment by cuboideum** [comment]
Just for the record: on second thoughts I have renamed the item from 'Bone Spicules' to 'Bone Spicules Characteristics' for the sake of coherence with other items. But I am awaiting your new solution which might change or resolve several of the issues that are currently open.

**Comment by JEB13** [comment]
Settled, I think?

**Comment by cuboideum** [comment]
The mixed module has been implemented.
