### ISSUE TITLE
'Cortex Perforated': Suggested change of name

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#26]
The Phaleron Paleopathology Scoring Key (Version 17 September 2021) defines the categorical data item 'Cortex Perforated'. It describes characteristics of added bone where bone formation processes have led to the perforation of the cortical surface (mostly the periosteal surface, I presume).

As a class name, 'Cortex Perforated' is not a very telling name. Could we change it to something indicating that the score refers to bone addition? What about 'Cortex Perforating Bone Addition'? I hope there will be better suggestions.

@JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by JEB13** [comment]
We had a lengthy and meaningful discussion of "cortex perforated" and while this organization devolves from my original configuration created in '92 or '93, I am willing to say that other systems are more robust.  We came up with a "mixed" category, which more realistically represents the spicules, the involucrum, the sequestrum, the shell, and the cloaca categories.  We also think that cranial porosity actually fits here.  Hannah (and I) are working on this mixed category and reducing bone addition/bone subtraction a bit -- I'm sorry, but this will be MUCH better.

**Comment by JEB13** [comment]
I believe this is settled?

**Comment by cuboideum** [comment]
The Mixed Bone Addition and Loss module has been implemented.
