### ISSUE TITLE
'Cortex Perforated' - 'Absent': Clarification of definition

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#27]
The Phaleron Paleopathology Scoring Key (Version 17 September 2021) defines the categorical data item 'Cortex Perforated'. The category designated with the numeric code 0 is called 'Absent'.

I assume that 'Absent', here, means that the cortex has not been perforated as a consequence of bone formation processes. Alternatively, the category could be interpreted to mean that none of the other two categories apply (i.e. that there is neither evidence for an expansive shell nor for a cloaca).

Is my interpretation correct?

Do the two categories really cover all cases of cortex perforation due to bone addition? Might a category 'Other' be necessary?

@JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by JEB13** [comment]
We had a lengthy and meaningful discussion of "cortex perforated" and while this organization devolves from my original configuration created in '92 or '93, I am willing to say that other systems are more robust.  We came up with a "mixed" category, which more realistically represents the spicules, the involucrum, the sequestrum, the shell, and the cloaca categories.  We also think that cranial porosity actually fits here.  Hannah (and I) are working on this mixed category and reducing bone addition/bone subtraction a bit -- I'm sorry, but this will be MUCH better.

**Comment by JEB13** [comment]
I think this is settled?

**Comment by cuboideum** [comment]
@hayesleigh and @cuboideum discussed this issue in a video conference on 10 August 2023. They agreed that it had become obsolete with the introduction of the 'Mixed bone addition and loss' section of the Pathology Module and that the issue could be closed.
