### ISSUE TITLE
Skull fragment section is not available 

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#3]
**Is your feature request related to a problem? Please describe.**
There is currently no section within the inventory for inputting the number of unidentified skull fragments. 

**Describe the solution you'd like**
A field to input the number of skull fragments would be helpful. 
**Describe alternatives you've considered**

**Comment by 15E601** [comment]
Unclassified fragments of the entire skull were already implemented in the ontology; I had merely forgotten to add the entry field in the app. The field is now available under the the cranium tab. However, the field does not save data for the moment, as I have switched the referenced class from
http://w3id.org/rdfbones/core#EntireSetOfBonesOfSkull
to
http://w3id.org/rdfbones/ext/phaleron-si/EntireSetOfCranialBones
The field will be fully functional once I have uploaded the new iteration of the ontology when all current ontology-related issues have been addressed.

**Comment by cuboideum** [comment]
I fail to understand the difference between rdfbones:EntireSetOfBonesOfSkull and phaleron-si:EntireSetOfCranialBones. The core ontology class refers to an element in the FMA, the phaleron-si class not. Why can't we use the core class?

**Comment by 15E601** [comment]
> I fail to understand the difference between rdfbones:EntireSetOfBonesOfSkull and phaleron-si:EntireSetOfCranialBones. 

As do I. The class was suggested by me and implemented by you in https://github.com/RDFBones/RDFBones-O/issues/142#issuecomment-892555726 - I assume we both simply overlooked the existing class? I that case, I will delete the phaleron class and replace all uses with the core class.

**Comment by cuboideum** [comment]
I guess you are right. I cannot remember a plausible reason for us introducing the new class.

Yes, go ahead using the core class and delete the other one. Is it referenced anywhere else?

**Comment by 15E601** [comment]
On second thought, the phaleron class is probably an artifact from before your change in the core ontology which I forgot to remove. I don't think it has any uses. If it does, I will simply switch them, as we both agree the phaleron class is redundant. I think we can close this issue again.

**Comment by cuboideum** [comment]
But please remove the phaleron class to avoid further confusion.

**Comment by 15E601** [comment]
> But please remove the phaleron class to avoid further confusion.

Yes, of course. I will also check if there are more instances of this issue, but I don't believe so.
