### ISSUE TITLE
'Mixed lesion location':Clarification of categories

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#32]
In the version of 23 September 2021, the palaeopathology template receives a new section 'Mixed Bone Formation and Bone Loss' in addition to 'Bone Addition' and 'Bone Loss'. This section contains the data field 'Mixed lesion Location' for which no categories are specified in the accompanying scoring key.

I assume that 'Mixed lesion Location' has the same categories as the data fields 'Bone Addition Location' and 'Bone Loss Location'. Is this correct?

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, please comment.

**Comment by HannahLiedl** [comment]
Yes, that is correct. I'm sorry, I didn't specify that in the key. I can add a quick explanation.

**Comment by cuboideum** [comment]
I think this resolves the issue and it can be closed without a formal 'go ahead'.

**Comment by JEB13** [comment]
Go ahead!  Have been following discussion!  Jane
________________________________
