### ISSUE TITLE
'Focal Bony Response': Clarification of categories

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#34]
The version of 23 September of the palaeopathology scoring key defines the data item 'Focal Bony Response' on page 5/6. This item depends on data item 'Type of Bony Response' as it only applies if 'Focal' was selected there.

The category denominated with the numerical code 0 is called 'Absent'. Does this mean that the bony response is not focal (implying that 'Diffuse' was selected for 'Type of Bony Response')? This would be redundant information. Or does 'absent' mean that none of the other categories (1 to 3) are applicable?

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, please comment.

**Comment by HannahLiedl** [comment]
Oh I see what you mean. I suppose the information is redundant in a way. If the "type of response" is "focal", you should specify what focal lesion it is. I usually put a 0 in for the diffuse bone loss then in order to not leave it blank. I suppose if we fill out the "focal bony response" the "type of response" becomes redundant. Or would it make it easier to find these kind of lesions?

**Comment by cuboideum** [comment]
I would suggest to leave the item 'Type of Bony Response' and only offer the item 'Focal Bony Response' if 'Focal' is selected.

In terms of RDF this would mean that there is always an instance of 'Type of Bony Response' while the presence of an instance of 'Focal Bony Response' depends on the label of the former. In other words, if 'Focal' is selected, the data item 'Diffuse Bony Response' is not offered for input and missing from the graph.

If this is the desired solution I suggest to drop the category '0 Absent'.

**Comment by HannahLiedl** [comment]
Yes, I think that is a good solution!

**Comment by JEB13** [comment]
Yes, implement!
________________________________

**Comment by JEB13** [comment]
Go ahead!

**Comment by cuboideum** [comment]
Fixed in commits leading up to RDFBones/Phaleron-Pathologies@66b3e95190215efb0f18d241d5d3aa66b0708bec.
