### ISSUE TITLE
'Diffuse Bony Response':Clarification of categories

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#35]
The version of 23 September of the palaeopathology scoring key defines the data item 'Diffuse Bony Response' on page 6. This item depends on data item 'Type of Bony Response' as it only applies if 'Diffuse' was selected there.

The category denominated with the numerical code 0 is called 'Absent'. As with 'Focal Bony Response' (cf. issue #34) it is unclear whether this refers to the absence of a diffuse bony response or to the absence of cortical thinning scored in categories 1 and 2.

The category denominated with the numerical code 9 is called 'Unobservable'. I assume that this is the case with bones that are not sections for sample taking (cf. Standards for data collection in human skeletal remains, p.118). Is this correct?

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, please comment.

**Comment by HannahLiedl** [comment]
As with issue #34 "absent" would mean absence of diffuse lesion (but this doesn't say anything about presence of focal lesion).
Unobservable is used when you cannot assess the cortical bone properly (e.g., complete bone).

**Comment by JEB13** [comment]
Yes, "absent" is absence of diffuse lesion.  "9" means cannot observe.

**Comment by cuboideum** [comment]
Fixed in commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
