### ISSUE TITLE
Cranial porosity data items

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#36]
The version of 23 September of the palaeopathology scoring key defines the following data items about cranial porosity on pages seven to nine:

* Cranial vault
     * Pitting severity
     * Pit density
     * Diploic expansion
     * Extent
     * Activity
* Orbits
     * Pitting severity
     * Pit density
     * Raised surface
     * Extent
     * Activity

All second-order items depend on whether porosity is observed in the cranial vault or the orbits, respectively. Following the functional principles of other sections, we could introduce the measurement data 'Presence of porosity in the cranial vault' and 'Presence of porosity in the orbits'. The second-order items, then, would only apply if 'present' is selected for these. With this solution we could drop the 'absent' categories for the dependent data items.

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, do you think this would be an improvement?

**Comment by HannahLiedl** [comment]
Yes, I think that is a good suggestions. I really like that we can have these optional items in the database. It makes everything much clearer than in the spreadsheet.

**Comment by JEB13** [comment]
Yes, that makes sense.  Please accept!

Jane
________________________________

**Comment by JEB13** [comment]
Go ahead!

**Comment by cuboideum** [comment]
@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh:

There are two ways of implementing this:

1. We add new data items ('Presence of cranial vault porosity', 'Presence of orbital porosity') to the scoring key.
2. We implement the optional aspects exclusively in the AnthroGraph data entry form.

I would strongly opt for alternative 1 for several reasons:

* We should have uniform data structures in all categories of the scoring key. This helps people working with the coding system.
* It is much easier to implement in RDFBones and AnthroGraph.

What do you think?

**Comment by cuboideum** [comment]
The requested changes are already implemented in the Phaleron-Pathologies ontology extension and in the AnthroGraph software.
