### ISSUE TITLE
'Lipping Degree': No 'absent' category

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#37]
The version of 23 September of the palaeopathology scoring key defines the data item 'Lipping Degree' on pages nine and ten. It does not have an 'absent' category while all other items in the 'OA and OP' section have one.

Does this mean that 'OA and OP' is only assessed if some form of lipping occurs? Or should there be an 'absent' category?

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, please comment.

**Comment by HannahLiedl** [comment]
I think there should be an "absent" option for lipping degree. It is possible to have porosity but no lipping.

**Comment by JEB13** [comment]
Yes, there should be an absent option for lipping degree.  GO AHEAD

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/bb2db84b3b3cc2273a2ea6ad372312bab210b591.
