### ISSUE TITLE
'Trauma Type' - 'Unknown, Unobservable, or Other

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#38]
The version of 23 September of the palaeopathology scoring key defines the data item 'Trauma Type' on page eleven. The category denominated with the numeric code 0 is called 'Unknown, Unobservable, or Other (e.g., stress)'.

This definition brakes with the scheme introduced with the other items where 'unknown' and 'unobservable' are coded as 9.

I suggest to rename the category denominated with the numeric code 0 to 'Other (e.g. stress)' and to add the category 'Unknown, unobservable' which is denominated by the numeric code 9.

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, what do you think?

**Comment by JEB13** [comment]
Again, we discussed this and rearranged the items such that "9" is unobservable, always.

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/c36ff51c8d050a2f888be467992aaacf41560475.
