### ISSUE TITLE
Usage of cortical bone within the pathology template

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#4]
**Is your feature request related to a problem? Please describe.**
There was confusion regarding if cortical bone should be applicable to the cranium/postcranium/or both. 

**Describe the solution you'd like**
Can you make cortical bone an option for bone loss region for both the cranium and the postcranium? 

**Additional context**
![bone loss](https://user-images.githubusercontent.com/90316213/132507471-b58883c2-1248-4122-85f0-f434cf627d47.png)

**Comment by cuboideum** [comment]
Fixed with commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.
