### ISSUE TITLE
'Fracture Sequelae': Categories

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#40]
The version of 23 September of the palaeopathology scoring key defines the data item 'Fracture Sequelae' on page thirteen. The category denominated with the numeric code 0 is called 'Unknown or Unobservable'.

This definition brakes with the scheme introduced with the other items where 'unknown' and 'unobservable' are coded as 9 (see also issues #38 and #39).

'Fracture Type' only applies if the lesion under observation has been classified as 'present' in data item 'Fracture Presence'. Even with fractures, sequelae might be present or not. So an option 'Not applicable' would make sense. Commonly, this would be coded as 0.

I suggest to rename the category denominated with the numerical code 0 as 'Absent'. I also suggest to add another category denominated with the numerical code 9 called 'Unknown, unobservable'. 'Fracture Sequelae' should be made dependent on 'Fracture Presence'.

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, what do you think?

**Comment by JEB13** [comment]
We discussed this and agreed on solution.

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/c36ff51c8d050a2f888be467992aaacf41560475.
