### ISSUE TITLE
'Timing of Injury': Categories

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#41]
The version of 23 September of the palaeopathology scoring key defines the data item 'Timing of Injury' on pages thirteen and fourteen. The category denominated with the numeric code 0 is called 'Unknown or Unobservable'.

This definition brakes with the scheme introduced with the other items where 'unknown' and 'unobservable' are coded as 9 (see also issues #38, #39 and #40).

Also, with timing of injury it might be helpful to have both 'unknown' and 'unobservable' categories.

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, what do you think?

**Comment by JEB13** [comment]
I believe that we discussed this and sorted it out?

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/c36ff51c8d050a2f888be467992aaacf41560475.
