### ISSUE TITLE
'Non-metric traits and/or Anomalies': Measurement datum or comment?

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#42]
The version of 23 September of the palaeopathology scoring key defines the data item 'Non-metric traits and/or Anomalies' on page fourteen. It is defined as follows:

> Just write the name of the non-metric trait. There is no coding for NMT.

This definition would make the data item a comment (cf. issue #31). If it was to be a measurement datum there would have to be a defined list of NMTs. Otherwise the meaning of a negative output (i.e. no names being written down) would be unclear.

If there was such a list, the data item could just as well be categorical measurement datum offering the list items for selection.

I assume that, here, the item is to be implemented as a specialised comment item.

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, is this correct?

**Comment by HannahLiedl** [comment]
Yes, we decided to just have this as a comment box. We never put together a list of NMTs as there are just too many to have a list of them in the database, I'm afraid. If we define a list of commonly found NMTs now it is possible or even likely that not all of the traits we would be defining now in a list were identified as people were not specificially looking for them. I suppose it is best at this point to stick with the comments box for NMTs even if it won't be possible to specifically search for them.

**Comment by JEB13** [comment]
Yes, Hannah is correct.  GO AHEAD and assume this is a comment item.

**Comment by cuboideum** [comment]
Implemented in the ontology extension with pull request https://github.com/RDFBones/Phaleron-Pathologies/pull/16.

**Comment by cuboideum** [comment]
Checking back with the AnthroGraph production instance shows that 'Non-metric traits and/or anomalies' has been implemented in the Phaleron App.
