### ISSUE TITLE
'Vertebral Pathology': Targeted regions of interest

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#43]
The version of 23 September of the palaeopathology scoring key defines a number of data items for the section 'Vertebral Pathology' on pages 16 and 17.

Most of these items record features for individual vertebrae. However, the categories '04 Ankylosis' in the data items 'Osteophyte Degree' and 'Syndesmophyte Degree' refer to two or three vertebrae. This raises the question what 'Vertebral Pathology' sections should be about, individual vertebrae or clusters of vertebrae.

There are several ways to solve this problem:

1. 'Vertebral Pathology' sections are initiated for individual vertebrae. Cases of Ankylosis are reconstructed during data analysis from those vertebra for which 'Ankylosis' categories have been selected.
2. 'Vertebral Pathology' sections are initiated for individual vertebrae. If a category 'Ankylosis' is selected, one or two other vertebrae can be defined as linked to the currently investigted vertebra through ankylosis.
3. 'Vertebral Pathology' sections are about individual vertebrae or clusters of vertebrae linked by ankylosis. All individual data items are then entered for each vertebra in the cluster, respectively.

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, which solution (or additional suggestion) would you prefer?

@zarquon42b and @15E601, what are your thoughts in terms of implementation in AnthroGraph?

**Comment by HannahLiedl** [comment]
I like option 2. Even if it is possible to identify the ankylosing vertebrae from the individual recording, this would make it clearer. However, we would also need an option in case the vertebra preservation is too poor and individual vertebrae cannot be numbered. In this case it should still be possible to count how many vertebrae are actually affected, just not if it is T1-T3 or T2-T4 for example.

**Comment by JEB13** [comment]
I agree with Hannah that option 2 is preferable.  However, we might have more than 1-2 vertebrae ankylosed.

**Comment by cuboideum** [comment]
Commit https://github.com/RDFBones/Phaleron-Pathologies/commit/3922316e8e875bbb27205c5be385f036f2291cff introduces a data item that can define up to two other regions of interest that a region of interest is permanently connected with.
