### ISSUE TITLE
Degree of Skull Fragmentation

### ISSUE THREAD

**Issue by 15E601** [RDFBones/RDFBonesPhaleron#44]
Leigh pointed out that the inventory was recording a specific number of fragments rather than recording whether or not the fragments numbered 50 or less.

I have fixed this issue with commit  RDFBones/Phaleron-SkeletalInventory@9757363 . The inventory now asks whether there are _lesser-equals 50_ or _greater 50_  fragments of the skull in the inventory. The relevant box can be found under the cranium tab.

**Comment by 15E601** [comment]
@hayesleigh Does this resolve your issue? Please keep in mind that I had to make a change in the ontology, which means that all inventories generated before the change no longer work.

**Comment by hayesleigh** [comment]
This does resolve the issue. Thank you!
