### ISSUE TITLE
OA&OP: Mockup

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#45]
This is a mockup for the OA&OP pathology section. It is based on the following assumptions:

* We can score individual anatomical regions of interest because articular surfaces do not stretch across several regions of interest.
* All kinds of observations (lipping, porosity, eburnation, osteophytes and periarticular resorptive foci) can occur together.

![phaleron-patho_OAandOP_Mockup-Section](https://user-images.githubusercontent.com/8103073/151336663-a2d202f8-a6ed-4053-b9b1-ca53f6ecd0ee.png)

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh: Is this what is expected? Do you have any suggestions for improvement?

**Comment by zarquon42b** [comment]
Please adapt to the current look & feel
![Test frontal  metaphactory  — Mozilla Firefox_001](https://user-images.githubusercontent.com/1515863/151790904-3b4279a4-c00b-441a-954b-fdc20a65f5d7.png)
.

**Comment by cuboideum** [comment]
During an RDFBones/AnthroGraph meeting on 31 January 2022 it was decided to model all Phaleron paleopathology modules with ROI specifications. The rationale behind this decision is to have uniform query structures across all modules.

**Comment by cuboideum** [comment]
The following version of the mockup includes an updated section taking contributions from researchers as requested by @zarquon42b in his [comment above](https://github.com/RDFBones/RDFBonesPhaleron/issues/45#issuecomment-1025669022) and a section for ROI specifications as requested by @zarquon42b and decided in the RDFBones/AnthroGraph workgroup meeting (cf. [comment above](https://github.com/RDFBones/RDFBonesPhaleron/issues/45#issuecomment-1026886652)):

![phaleron-patho_OAandOP_Mockups-Section](https://user-images.githubusercontent.com/8103073/151984663-1dab7fd6-472e-4b9f-a7eb-9daaa2ac5e34.png)

Modelling the OA&OP module with ROI specifications proves difficult as here specifications are different from the ones in the Bone Addition and Bone Loss modules:

* ROI specifications need to be about one single ROI
* Each observation is about exactly one ROI specification
* The mesurement datum "Anatomical Site" is not part of the specification.
* There are several items of the type "Extent of Involvement": Lipping Extent, Porosity Extent, Eburnation Extent and Periarticular Resorptive Foci Extent.
* Whether the "Extent of Involvement" items are to be filled or not depends on the corresponding "Degree" items: Lipping Degree, Porosity Degree, Eburnation Degree and Periarticular Resorptive Foci Degree. Most of these include the option 'Absent', rendering the corresponding "Extent of involvement" item useless.

These observations invalidate arguments for modelling all modules with ROI specifications.

* ROI specifications for the OA&OP module need to have a different structure from specifications for other modules. As a consequence, it is impossible to have a uniform query extracting ROI data from all modules.
* With the OA&OP module, ROI specifications would have to be registered after the coding of observational data because these determine which specification items are relevant. This workflow would go against the intuitive workflow of investigations and be different from the structure of other data entry forms.

Using ROI specifications with the OA&OP module would be an attempt to create uniform structures to support software implementation while it does not make sense in terms of the investigation to be modelled. This is in conflict with our tenet that semantic data modelling and querying should be determined by what data mean, not by the database structure.

I, therefore, suggest to revert the decision of 31 January 2022 and return to straight modelling of ROIs. @zarquon42b and @15E601, what do you think?

**Comment by cuboideum** [comment]
Alternative mockup version without ROI sections (cf. discussion in [comment above](https://github.com/RDFBones/RDFBonesPhaleron/issues/45#issuecomment-1026914254)):

![phaleron-patho_OAandOP_Mockups-SectionWithoutROISpecs](https://user-images.githubusercontent.com/8103073/151997913-1c502c21-683e-40ea-8c41-c3742ea48ed0.png)

**Comment by cuboideum** [comment]
Updated version including feedback from @HannahLiedl in a [comment](https://github.com/RDFBones/RDFBonesPhaleron/issues/46#issuecomment-1027189229) to #46. Here, 'Lipping' also has a conditional 'Extent' item, just as the other data items.

![phaleron-patho_OAandOP_Mockups-SectionImprovedLippingItems](https://user-images.githubusercontent.com/8103073/152114519-18e86541-da0d-41d5-821b-086910220bb3.png)

**Comment by HannahLiedl** [comment]
I'm not fully sure I follow the issue here. Would it not be possible to identify the ROI (e.g., L humerus) and then the anatomical aspect (proximal or distal)? OA would only appear on joint surfaces, so this would make sense to me.

**Comment by cuboideum** [comment]
> I'm not fully sure I follow the issue here. Would it not be possible to identify the ROI (e.g., L humerus) and then the anatomical aspect (proximal or distal)? OA would only appear on joint surfaces, so this would make sense to me.

For this reason, we do not necessarily need ROI specifications for the OA&OP module. Of course, data queries differ considerably between modules that lump several ROIs with a ROI specification and others that reference individual ROIs directly. To have the same query structure for all pathology modules was the motivation to keep ROI specifications. So this decision was made exclusively in respect to technical aspects (data query) and not to aspects pertaining to the investigation. This is what I am referring to in my [comment above](https://github.com/RDFBones/RDFBonesPhaleron/issues/45#issuecomment-1026914254).

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/RDFBonesGraphics/commit/b081061a4fa780592d5f034135c7b80849543f67.
