### ISSUE TITLE
'Timing of Injury': Make categorical data item distinct?

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#47]
The Phaleron Paleopathology Scoring Key (version 03 February 2022) defines the data item 'Timing of Injury' on page 13. The instruction reads "Select all that apply.", implying that several categories can be selected at the same time.

The defined categories are 'Unknown', 'Antemortem', 'Perimortem' and 'Unobservable'.

I intuitively have modelled this as a distinct item, i.e. coders have to opt for exactly one category. Only now I realise that it had been defined otherwise.

To my understanding, co-occurrence of categories is impossible, given that we decided to understand 'Unknown' as 'ambiguous evidence' and 'Unobservable' as 'no evidence'.

I suggest to make the data item distinct.

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, what do you think?

**Comment by HannahLiedl** [comment]
I agree. It should be "select one" for timing of injury.

**Comment by cuboideum** [comment]
In a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 15 February 2022 it was decided to make the measurement datum distinct. @HannahLiedl will change the Phaleron scoring key and I will implement the new version in the ontology extension.

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/d3712615a7f0b8e118f198e543c4d8a9f0895fe5.
