### ISSUE TITLE
Mixed Bone Formation & Loss: Extent of traces

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#48]
In the Phaleron Paleopathology Scoring Key (version 2022-02-15) the section 'Mixed Bone Formation and Bone Loss' starts as follows:

> Location/extent etc.

The Phaleron Paleopathology Template (version 2021-09-23), on the other hand, features just the following data fields:

* Within Bone Location (a.k.a. 'Anatomical aspect')
* Mixed lesion Location (a.k.a. 'Anatomical site')

A data field describing the extent of the entire lesion is missing.

Both scoring key and template have 'extent' items for the following features:

* Sunburst effect
* Cauliflower appearance
* Expansive shell
* Sequestrum
* Involucrum
* Cloaca from medullary cavity
* Cranial vault porosity
* Orbital porosity

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh:

Should there be an 'extent' item for the observed lesion as a whole as implied by the scoring key or just 'extent' items for the specific features as included in the template?

**Comment by hayesleigh** [comment]
Jane and I discussed and we agree it should be as a whole not just the individual characteristics

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/3aa36843916f18b31240ebbcadb891c2442114f6.
