### ISSUE TITLE
Taphonomy regions

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#5]
**Is your feature request related to a problem? Please describe.**
The current system of recording taphonomy for every single element is too detailed and recording per region is sufficient for our purposes.

**Describe the solution you'd like**
Recording of taphonomy can follow the same categories as the skeletal inventory:
- Skull
- vertebral column
- thorax (ribs and sternum)
- pectoral girdle
- L upper limb
- R upper limb
- L hand
- R hand
- pelvic girdle
- L lower limb
- R lower limb
- L foot
- R foot

**Comment by zarquon42b** [comment]
This would need a complete overhaul of the SI section and we need to remove the `PSI_SI_MD_FormTripletSnippet` and replace it with an equivalent `PSI_SI_MD_FormTupelSnippet`  and then change all sections accordingly.
Then we would need to create TaphonomySnippets and add them to the forms.
@15E601 would you be willing/have time to do the replacement/adding part?

**Comment by 15E601** [comment]
Yes, I will take care of this. It also requires additional classes in the ontology, which I will add.

**Comment by zarquon42b** [comment]
I have already created `PSI_SI_MD_FormTupelSnippet` and `PSI_SI_MD_FormTupelGUISnippet` so you can search and replace and then manually remove the taphonomy variable definition.
E.g.:
`[[>:PSI_SI_MD_FormTripletSnippet MyID_Comp="frontalleftorbitalcomp" MyID_Obs="frontalleftorbitalobs" MyID_Taph="frontalleftorbitaltaph" ROIVar="<http://w3id.org/rdfbones/ext/phaleron-si/LeftOrbitalPartOfFrontalBone>" ]]             `  

will become
`[[>:PSI_SI_MD_FormTupelSnippet MyID_Comp="frontalleftorbitalcomp" MyID_Obs="frontalleftorbitalobs" ROIVar="<http://w3id.org/rdfbones/ext/phaleron-si/LeftOrbitalPartOfFrontalBone>" ]]               `

**Comment by 15E601** [comment]
@cuboideum I require the following classes for the core ontology:

'Entire vertebral column' - related to fma13478
'Entire thorax' (we possess 'Entire set of all ribs', but this does not include the sternum and hyoid) - related to fma99576
'Entire shoulder girdle' - related to fma23217
'Entire left upper limb' - related to fma24896 (or fma7186?)
'Entire right upper limb' - related to fma24895 (or fma7185?)
'Entire hip bone - related to fma16585' (or fma 15681?)
'Entire left lower limb' - related to fma24981 (or 7811?)
'Entire right lower limb' - related to fma24980 (or 7187?)

**Comment by JEB13** [comment]
Where is the sacrum (and coccyx) -- with vertebrae?

**Comment by JEB13** [comment]
Pelvic girdle better than hip bone?

**Comment by HannahLiedl** [comment]
The sacrum is with the vertebral column in the inventory. I suppose it would be simpler to have it with the vertebral column in the taphonomy section, even if it might be closer to the ossa coxae in terms of taphonomic changes? Thoughts?

**Comment by JEB13** [comment]
It makes sense in terms of the inventory/function, but in terms of contextual location for taphonomic changes, the probability of common conditions would be more like the hip bones.  Other thoughts?  I don't have strong feelings about this, but thought I should raise the issue.

**Comment by 15E601** [comment]
@JEB13 In the FMA the sacrum is not part of the hip bone but a subdivision of the vertebral column. I would have suggested to keep it the same way here to stick with the FMA scheme, but I do see your point about taphonomy. Ultimately the question is what makes most sense to you as the users. As it sounds to me, what is most intuitive for taphonomy is to have the sacrum and coccyx be part of the hip bone and then call this segment "pelvic girdle". If you agree, we should perhaps point this out in a tooltip when we implement it.

@cuboideum None of the classes I proposed in this issue are in RDFcore in any way - as per our discussion yesterday, I will instead add the classes to the Phaleron inventory, is that right?

**Comment by cuboideum** [comment]
> @JEB13 In the FMA the sacrum is not part of the hip bone but a subdivision of the vertebral column. I would have suggested to keep it the same way here to stick with the FMA scheme, but I do see your point about taphonomy. Ultimately the question is what makes most sense to you as the users.

I strongly agree. For the development of RDFBones, we try to stick to the FMA logics as close as possible in order to create a coherent resource that does not confuse users. The phaleron ontology extensions and apps should only focus on the requirements of the Phaleron Bioarchaeological Project.

**Comment by cuboideum** [comment]
> @cuboideum None of the classes I proposed in this issue are in RDFcore in any way - as per our discussion yesterday, I will instead add the classes to the Phaleron inventory, is that right?

Go ahead.

**Comment by JEB13** [comment]
GO ahead!

I just found that somehow RFD Bones is going into junk mail for me.  ARGH!!

Yes, pelvic girdle, obviously, sacrum/coccyx not part of hip bone.  Vertebral column is correct biologically, of course.

Jane
________________________________

**Comment by 15E601** [comment]
Revised taphonomy fields are now implemented. If there are any problems with it you can always re-open this issue.
