### ISSUE TITLE
Bone add/loss no options available under ROI specification

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#50]
**In what module does the bug occur?**
What module (e.g. 'Skeletal Inventory', 'Palaeopathology') are you working with? Please indicate what section (e.g. tab, skeletal region) is affected. You can also provide the URL of the data entry page.
 Within the bone addition and the bone loss sections in the paleopathology module, certain regions do not have options listed under the ROI specification. 

We encountered this error specifically in the thorax and shoulder girdle sections. Tried refreshing the page and this did not resolve the issue.

![ROI specification no option](https://user-images.githubusercontent.com/90316213/156236145-ad0a7cad-821b-4b89-92a3-5d25dd804c3d.png)

**Comment by cuboideum** [comment]
The problem was a namespace error in the Phaleron app ontology (cf. issue https://github.com/AnthroGraph/Phaleron-AppOntology/issues/8). Fixed with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/65f0e79e76f188d326b8e0743eb776672ad31267.
