### ISSUE TITLE
New ROI specification-failure to save?

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#51]
The bug occurs in the Paleopathology section-Bone Addition. 

https://anthrograph.anthropologie.uni-freiburg.de/resource/?uri=http%3A%2F%2Fpbp-paleoppath.org%2Frecords%2FPathologyDatasetSection-1b4f6c3c-dab8-4c62-82e4-15337906d372

Everything works well for the first ROI but when I save and go to add a new ROI the old ROI is still in the new ROI spot. I try saving and it doesn't fix the problem. Leaving the page and returning also doesn't help, if I change the ROI with the old one still in the slot it deletes the first one. It doesn't happen every time. May just be a user error.

**To Reproduce**
I created a new label.
Entered in the new ROI Specification-click save
Enter in the Added Additional Info
I then created a new observer/editor role and save
Return to the main form
The old ROI is still in the new ROI specification slot
I return to paleopath summary
Re-enter the page
Old ROI is still in the new ROI specification slot

4. 
![image](https://user-images.githubusercontent.com/90316213/157315285-24bc4be0-8c1a-4c44-b7e7-64c7513c4907.png)

**Comment by zarquon42b** [comment]
I guess you will need to either confirm the Form data recovery notice by clicking one of the two options:
![157315285-24bc4be0-8c1a-4c44-b7e7-64c7513c4907](https://user-images.githubusercontent.com/1515863/157316442-c3973604-c2d3-4213-8f42-d2d6d58f37aa.png)

**Comment by zarquon42b** [comment]
Can this issue be closed now?

**Comment by hayesleigh** [comment]
Hi all,

I tested this issue and clicking the button does not resolve problem. Sorry
for the late response.

**Comment by 15E601** [comment]
As coincidence has it, I am currently attempting to find the ROI of OA&OP observations (for the Rowers Project). I cannot find them. I have reason to believe that the ROI is not being recorded in the named graph at all.

My dummy data uses "Body of C3", but the only "is about" statement I can find is "[...]PhaleronVertebralColumnArticularROIs". Where is the link to the Body of C3 ROI supposed to be?

**Comment by 15E601** [comment]
For reference, here the missing connection
![dummy_OAOP_bug](https://user-images.githubusercontent.com/67172847/157698087-041a5f5c-48fe-4160-aa52-855c90b402a4.png)

**Comment by 15E601** [comment]
Right, I played around some more, and now it works. The first time I tried saving it, I also got the browser recovery message. Now I don't get it, and it works correctly. I get the feeling it's Metaphacts that's being a bit peculiar with inputs sometimes? I have no explanation.

**Comment by cuboideum** [comment]
We discussed this issue during a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph project group on 15 March 2022. As the problem does not occur consistently, it is unclear what can be done about it. We agreed on closing it for now, with an option for reopening if the problem was to re-occur frequently.
