### ISSUE TITLE
No ROI showing up for grouped elements

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#52]
Hi all, 

Within the pathology sections, it would be nice to have ROI specifications that include grouped elements. 

Especially with the ribs and vertebrae, it might not be possible to identify the element specifically, but it is still present and might have pathologies associated. Currently, I included the pathologies on grouped elements in the notes section of the relevant region. Might be good to discuss this at the meeting next week. 

![image](https://user-images.githubusercontent.com/90316213/157915462-8714e4ca-aee8-4681-8575-54d40f11255e.png)

**Comment by cuboideum** [comment]
We discussed this issue during a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph project group on 15 March 2022. At the bottom of the Phaleron Paleopathology Template, there are some lines defining regions of interest that refer to groups of bones. Meeting participants also came up with additional suggestions. This is the full list:

* Vertebrae grouped (nine items as defined in the Pathology Template)
* Ribs grouped (four items as defined in the Pathology Template)
* Hand phalanges (six items as defined in the Pathology Template)
* Foot phalanges (six items as defined in the Pathology Template)
* Cranial vault
* Long bones

**Comment by cuboideum** [comment]
@HannahLiedl: Will you create a new version of the template to mirror the addition of grouped ROIs?

**Comment by HannahLiedl** [comment]
Jessica and I updated the forms on the google drive. Adult and non-adult should both look the same now for the new ROIs.

**Comment by cuboideum** [comment]
The following items are in the template but not currently implemented in AnthroGraph:

Vertebrae:

- \# Neural arch fragments
- \# Body fragments

**Comment by cuboideum** [comment]
Currently, the Phaleron skeletal inventory does not identify bone fragments as part of the cranial vault. Instead, there is an estimate whether there are more or less than 50 unidentified fragments from the entire skull. The ROI used for this, 'Entire set of cranial bones' (phaleron-si:EntireSetOfCranialBones),  has to be used, instead.

**Comment by cuboideum** [comment]
Pull request https://github.com/RDFBones/RDFBones-O/issues/194 creates anatomical regions of interest to be referenced by measurement data yet to be implemented in skeletal inventory.

**Comment by cuboideum** [comment]
Commits https://github.com/RDFBones/RDFBonesGraphics/commit/a16e63315857c8d9cf868ff6bf72f71af15feb59, https://github.com/RDFBones/RDFBonesGraphics/commit/0f78331be3ce0744bff598d4fa9ca337b5414985 and https://github.com/RDFBones/RDFBonesGraphics/commit/b618fa17c1bb9eada9f83510db07c64714ef4520 add details about the pattern to be implemented to the phaleron-si building plan.

**Comment by cuboideum** [comment]
The Phaleron-SkeletalInventory ontology extension already has class restrictions to class 'Inventory section vertebral column' (phaleron-si:AdultVertebralColumn) prescribing counts of unclassified fragments from neural arches and vertebral bodies:

```
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000051"/>
                <owl:someValuesFrom>
                    <owl:Class>
                        <owl:intersectionOf rdf:parseType="Collection">
                            <rdf:Description rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/NumberOfUnclassifiedFragments"/>
                            <owl:Restriction>
                                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000136"/>
                                <owl:qualifiedCardinality rdf:datatype="http://www.w3.org/2001/XMLSchema#nonNegativeInteger">1</owl:qualifiedCardinality>
                                <owl:onClass rdf:resource="http://w3id.org/rdfbones/ext/phaleron-si/EntireNeuralArchOfVertebra"/>
                            </owl:Restriction>
                        </owl:intersectionOf>
                    </owl:Class>
                </owl:someValuesFrom>
            </owl:Restriction>
        </rdfs:subClassOf>

```
```

        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000051"/>
                <owl:someValuesFrom>
                    <owl:Class>
                        <owl:intersectionOf rdf:parseType="Collection">
                            <rdf:Description rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/NumberOfUnclassifiedFragments"/>
                            <owl:Restriction>
                                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000136"/>
                                <owl:qualifiedCardinality rdf:datatype="http://www.w3.org/2001/XMLSchema#nonNegativeInteger">1</owl:qualifiedCardinality>
                                <owl:onClass rdf:resource="http://w3id.org/rdfbones/ext/phaleron-si/EntireBodyOfVertebra"/>
                            </owl:Restriction>
                        </owl:intersectionOf>
                    </owl:Class>
                </owl:someValuesFrom>
            </owl:Restriction>
        </rdfs:subClassOf>
```

But, here, the measurement data are specified to be about individual neural arches and vertebral bodies. As the actual data item describes fragments from a range of vertebrae, the about statements need to reference the ROIs representing Entire sets of neural arches and vertebral bodies.

**Comment by cuboideum** [comment]
The remaining implementation in AnthroGraph is covered by issue https://github.com/AnthroGraph/PBP-App/issues/70.
