### ISSUE TITLE
No new entry field appearing after save 

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#53]
**In what module does the bug occur?**
Within the trauma section of the paleopath module, no new entry field appears after I save the sub-form. This has occurred in both trauma entries I tried to record so far. I tried clicking save several times and a new field doesn't show up. Is it supposed to be the fracture sequelae? 

https://anthrograph.anthropologie.uni-freiburg.de/resource/?uri=http%3A%2F%2Fpbp-paleoppath.org%2Frecords%2FPathologyDatasetSection-68eec2b5-57a4-46a1-9199-1ab173728ec5

![image](https://user-images.githubusercontent.com/90316213/158229511-a727161e-cfb1-445f-8084-629a369ed2d2.png)

**Comment by cuboideum** [comment]
If you code 'Presence of fracture' as 'Present', two additional data fields, 'Type of fracture' and 'Fracture sequelae' are expected to appear.

Please verify this with a case that does involve fracture.

In addition, we can rephrase the info note to clarify that the appearance of additional data fields depends on the 'Presence of fracture' field.

**Comment by hayesleigh** [comment]
It does not involve a fracture, so that explains it. Thank you for the
clarification.

**Comment by cuboideum** [comment]
Currently, the info note reads as follows:

> After saving this sub-form, new entry fields may appear below - depending on the selected input.

This should be less confusing than the original note.
