### ISSUE TITLE
Creator of Inventory

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#54]
**Is your feature request related to a problem? Please describe.**
I tried to put in an inventory, but my name is not an option for Creator of Inventory. I also see a problem if someone is adding an inventory that was collected by someone else, as it will be difficult to differentiate who put the data in and who collected it if everyone is called "creator of inventory".
The same applies to the date, as it should be possible to add two dates (data collected and inventory added to database).

**Describe the solution you'd like**
Can we please have the names of all data collectors added to the database?
Can we add a second date field to distinguish between the two events?

**Comment by cuboideum** [comment]
@zarquon42b: I think we opened registration of researchers to all users so that people can register themselves, correct?

What were our latest decisions concerning dates for dataset creation?

**Comment by cuboideum** [comment]
@hayesleigh and @cuboideum discussed this issue in a video conference on 10 August 2023. They agreed that it had become obsolete with the introduction of research contribution processes that allow for role assignment and notes specific to each contribution. The issue is, therefore, closed.
