### ISSUE TITLE
Skull Inventory - Neurocranium

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#55]
**Is your feature request related to a problem? Please describe.**
For the inventory of frontal bone - pars orbitalis, the header says pars petrosa.

**Describe the solution you'd like**
Can we please correct the pars petrosa in the frontal bone inventor to pars orbitalis.

**Comment by 15E601** [comment]
Fixed in https://github.com/AnthroGraph/PBP-App/pull/31
