### ISSUE TITLE
Skull Taphonomy

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#56]
**Is your feature request related to a problem? Please describe.**
When entering skull taphonomy, I can only enter one option, e.g., in fragments. It is possible to have more than one type of taphonomy in the skull.

**Describe the solution you'd like**
Can we please add multiple options for the skull taphonomy?

**Comment by 15E601** [comment]
Fixed in https://github.com/AnthroGraph/PBP-App/pull/31
