### ISSUE TITLE
Walker and Klales Estimates unclear in Template

### ISSUE THREAD

**Issue by 15E601** [RDFBones/RDFBonesPhaleron#57]
The  "Sex Estimation Template" (and the scoring key) expects a single entry for the Walker- and Klales statistical sex estimates. Walker produces up to 6 different values (gl-ma-me, gl-ma, etc.), Klales up to 5. How is the final, single value produced?

I'm assuming that, like the final overall estimate, it's a non-mathematical assessment based on all values available in the respective method. For the data model, this would mean that, for e.g. Walker, all values entered are inputs for the decision-making-process that has its value put in the cell "Walker (2008) Statistical Sex Estimate (Male or Female)". Is that correct?

**Comment by HannahLiedl** [comment]
For these, we score the specific traits and then put these values in the respective discriminate function. Based on the values you get, I decide on one of the options (f, poss f, ambig, poss m, m). I do not record each of these values individually in the data spreadsheet.

**Comment by 15E601** [comment]
I see. Would you still want the option to input all values, or should you only get to choose one for Klales and Walker each?

**Comment by HannahLiedl** [comment]
I don't know if everyone is agreeing with me on this but the way I would do it:

Score for Klales, 2012:

Ventral Arc (1-5)
Subpubic concavity (1-5)
Ischiopubic ramus bridge (1-5)

Score for Walker (2008)
Nuchal Crest (1-5)
Mastoid Process (1-5)
Supraorbital margin (1-5)
Glabella (1-5)
Mental eminence (1-5)

These would be scored anyways even if we did no use the discriminate functions provided by Klales and Walker, so these have to be in the database. However, what I was thinking is, that we would not need the actual function in the database, but have these as a separate file in excel as we do right now. So the process would be: score in the database, go to the function in excel and enter the data, and then put the result (male/female) in the space provided in the database. This means we would need a field for Klales and Walker each, where we can put in the result. Does this make sense?

**Comment by 15E601** [comment]
Makes sense so far. My plan currently is to give the option to enter multiple discriminate functions if desired, or leave it at 1 (or 0). Calculating the functions within Metaphacts is probably possible, but for the moment it's outside my capabilities, so calculating in Excel will likely be necessary.

Another question: how do you come to a conclusion for the field "Overall Morphological Estimation"? I assume that again you look at all the values entered and then make a judgement on that; there is no rule-of-thumb or statistical method?

**Comment by 15E601** [comment]
I should clarify:
I am again trying to work out the data model. The excel sheet for "SEX ESTIMATION TEMPLATE" leads me to believe that all values visible on the page are involved in the process of finding the Overall Morphological Sex Estimation value. So even though, for example, there is a statistical sex estimate for the Klales method (assuming it could be calculated), the scores of 1-5 for the ventral arc etc. should also be considered a data item that is used (or rather: _can_ be used) in the process. Everything is fair game.
Is that right?

**Comment by HannahLiedl** [comment]
So, we decided this week that we will no longer be using the Walker function. It just doesn't work for our population. We will still be scoring the same values for the cranium, just no longer put it in the function. That means not much should change on your end. We just would not have a field to put in whatever the Walker function was spitting out. I'm sorry, there was so much going on this week, I just didnt find the time yet to update everyone and the spreadsheets.

Generally with sex estimation (as with age) it is a bit of a weighing the different observations I have to come to the best conclusion. So I would score whatever I can and then put my estimation in the "overall estimation". We would usually put some explanation in the notes. It is for example possible that the pelvis is more male and the cranium has a more female morphology. I then would have to evaluate all my observations to come to a conclusion.

**Comment by cuboideum** [comment]
@15E601: Is this resolved?

**Comment by 15E601** [comment]
I was waiting to close this until I had pushed the sex estimation module, but I think we're safe to do so now.
