### ISSUE TITLE
Conflicting options for spondylolysis location

### ISSUE THREAD

**Issue by 15E601** [RDFBones/RDFBonesPhaleron#58]
Felix did not model a location datum for spondylolysis in the vertebral pathology section, which surprised me, as I possess a template which asks for this datum (the column "spondyloylsis: location". Felix' template (from 27th Sept. 2021) has instead 2 columns that are each called "spondyloylsis: degree", along with a third column "spondylolysis presence". The template appears to have been removed from the google drive.

@HannahLiedl is this simply a typo in Felix' template?

**Comment by cuboideum** [comment]
During a meeting on 12 April 2022 it was decided that location of spondylolysis should be defined by the region of interest that the observation is based on. An additional 'location' item is not necessary.
