### ISSUE TITLE
Dental eruption

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#59]
**Is your feature request related to a problem? Please describe.**
As we have it now in the dental inventory recording form, the development and eruption is greyed out for all permanent teeth except for M3s. This has made sense for me so far as I've been working on adults with fully developed dentition, but I'm currently working on an individual with mixed dentition and not all of the permanent dentition is fully formed and erupted, meaning I have to fill this out for more teeth.

**Describe the solution you'd like**
Maybe this is redundant and you already talked about this in the last meeting when I had to leave early, but it should be possible in the database dental inventory, to record dental development and eruption for all permanent teeth. It is easy in the spreadsheet to just fill out the greyed out cells too, but that would not be an option in the database.

If you already discussed this and this is no longer an issue, you can just close this.

**Comment by cuboideum** [comment]
> It is easy in the spreadsheet to just fill out the greyed out cells too

This is not a solution. The cells are greyed out so that they cannot be filled. We need a decision on whether permanent teeth in development are to be scored or not.

I do not see why they should not. How was this handled for the dental inventories that have already been completed?

**Comment by HannahLiedl** [comment]
The forms are updated on the drive accordingly.

**Comment by cuboideum** [comment]
Great. We will implement the updated version (27 April 2022).
