### ISSUE TITLE
Recording of unobservable elements

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#6]
**Is your feature request related to a problem? Please describe.**
For some elements it is impossible for us to record degree of presence due to taphonomic factors such as sediment encasing. These elements are present, but we cannot use the current options "complete", "partial", and "poor".

**Describe the solution you'd like**
Is it possible to add another option for presence/absence "en block/not observable"?

**Comment by 15E601** [comment]
As per issue #5, we also face the fact that the taphonomic description of en bloc will be independent of the degree-of-presence en bloc, if we were so to call it. That may confuse.

Either way, perhaps "Not discernible" is a better name for the option. Is this acceptable?

**Comment by HannahLiedl** [comment]
I'll bring it up at the project meeting tomorrow for discussion. Thank you!

**Comment by HannahLiedl** [comment]
Yes, we agreed to the option "not discernible" as option. Thank you!

**Comment by JEB13** [comment]
Yes, implement -- or whatever the key phase is.

**Comment by 15E601** [comment]
"Not discernible" implemented as fifth option for completeness.
