### ISSUE TITLE
Dental Inventory: Add presence and observability rating for dental alveoli

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#63]
The dental pathologies module contains elements that require evidence from dental alveoli. The dental inventory, however, only rates presence and observability of teeth and tooth positions.

During meetings between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 12 and 26 April 2022 it was discussed and decided to add rating of dental alveoli to the dental inventories of both deciduous and permanent teeth. The levels for this assessment should be as follows:

1. present
2. absent
3. unobservable

@HannahLiedl, I tried to assign this issue to you but could only select organisation members. I have issued a team invitation. I hope you will be on board once you accept it.

**Comment by HannahLiedl** [comment]
Dental recording is updated

**Comment by cuboideum** [comment]
> Dental recording is updated

Great, we will start implementation.
