### ISSUE TITLE
Add 'Number of unclassified tooth fragments' to template

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#65]
At the meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 24 May 2022 it was decided to add a data item 'Number of unclassified tooth fragments' to the Phaleron Dental Inventory Template.

**Comment by HannahLiedl** [comment]
"Unclassified tooth fragments (#)" added to dental inventory. It is the file "Update Dental Inventory Template 25.05.2022"
