### ISSUE TITLE
Data recovered from browser storage

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#66]
**In what module does the bug occur?**
IV_743, Skeletal inventory. Arm. Leg
 
**Describe the bug**
For the left humerus and the right patella the following shows up in the skeletal inventory of IV_743: "Form Data has been recovereed from browser storage".

**To Reproduce**
1. Go to 'IV_743'
2. Click on 'Arm' or 'Leg'
3. Scroll down to 'L humerus' or 'right patella'

**Expected behavior**
I just don't think this should be happening. I would have to click on "save" before I can move on to the next bone, so this should have been saved in the initial recording?

**Screenshots**

![Screenshot (3)](https://user-images.githubusercontent.com/90314688/173223459-0c892b30-5c15-44be-a494-43b9eed32d01.png)

**Comment by zarquon42b** [comment]
Your issues are very likely owed to a bad internet connection on your part during data entry: If there is no connection to the server when pressing "Save" the data cannot be sent to the database. However, the selected values stay in the browser cache and you are informed upon reloading the page. In your example IV_743 there were no values saved at all for left humerus (indicating that the save event was not successful). I could enter and save the data from your screenshot without issues.
