### ISSUE TITLE
ROI discrepancies between Skeletal Inventory and Sex Estimation module

### ISSUE THREAD

**Issue by 15E601** [RDFBones/RDFBonesPhaleron#67]
ROIs addressed by Sex Estimations do not correspond directly to the ROIs recorded in the Skeletal Inventory. For the origin of data to be clear, the scores recorded in the estimation must be linked to a ROI of the skeletal inventory. This causes a two-fold issue.

First, it means I need to approximate the ROIs, which I intend to do as follows:

Ventral Arc -> Left **OR** Right Pubis
Subpubic Concavity -> Left **OR** Right Pubis/Ischium
Ischiopubic Ramus Ridge -> Left **OR** Right Pubis/Ischium

Greater Sciatic Notch -> Left **OR** Right Ilium

Nuchal Crest -> Squamous Part Of OccipitalBone
Mastoid Process -> Left **OR** Right Petrous Part Of Temporal Bone
Supraorbital Margin -> Left **OR** Right Orbital Part Of Frontal Bone
Supraorbital Ridge/Glabella -> Left _AND_ Right Orbital Part Of Frontal Bone
Mental Eminence -> Left _AND_ Right Side Of Mandible

If these ROIs are acceptable (I'm especially unsure about Ventral Arc and Ramus Ridge), then the second issue is how to decide whether the ROI is complete enough for the sex estimation to be performed (if at all). I see 3 options:

1) Rework the skeletal inventory to include the ROIs addressed by the sex estimations

2) Link to the ROIs in the skeletal inventory as suggested above, but ignore completeness status; you can enter a value even if every ROI is noted as "missing"

3) Link to the ROIs in the skeletal inventory as suggested above, and check if the status is "missing or "not discernible"; if not, it will be deemed eligible for use in sex estimation. Otherwise the interface will only allow you to select "evaluation not possible"

Option 1) is obviously out of the question. 2) is easiest to implement, but allows nonsensical information to be entered (such as a sciatic notch score for a skeleton with no ilium). 

3) allows us to prevent nonsensical information. In cases where an element uses 2 ROIs of the inventory, this can get tricky. I think we should say that both ROIs need to be "poor" or better, but if people disagree on which ROIs must be present to make an estimate, then this can be a point of frustration.

If option 3) is preferred over 2), then the question of which ROIs of the skeletal inventory are referenced is highly important.

**Comment by HannahLiedl** [comment]
@JEB13

**Comment by JEB13** [comment]
For the following:

Ventral Arc -> Left OR Right Pubis **YES JEB**
Subpubic Concavity -> Left OR Right Pubis/Ischium **I THINK THIS COULD BE SCORED FROM EITHER A PUBIS OR AN ISCHIUM, DEPENDING ON FRAGMENT, BUT PRIMARILY PUBIS.  I WOULD NOT WANT IT TO BE IMPOSSIBLE TO SCORE IF AN ISCHIUM IS NOT PRESENT.  SO SHOULD BE AVAILABLE TO SCORE IF EITHER PUBIS OR BOTH PUBIS/ISCHIUM ARE PRESENT.**
Ischiopubic Ramus Ridge -> Left OR Right Pubis/Ischium **(DITTO) I THINK THIS COULD BE SCORED FROM EITHER A PUBIS OR AN ISCHIUM, DEPENDING ON FRAGMENT, BUT PRIMARILY PUBIS.  I WOULD NOT WANT IT TO BE IMPOSSIBLE TO SCORE IF AN ISCHIUM IS NOT PRESENT.  SO SHOULD BE AVAILABLE TO SCORE IF EITHER PUBIS OR BOTH PUBIS/ISCHIUM ARE PRESENT.**

I think the ilium is sufficient for GSN and the skull ROIs are fine.

I prefer option 3, as per above.  Is this a problem?  I think the pubis needs to be there for all three pubic features.  The ischium is value added.  For subpubic concavity and IP ridge, I suppose allowing it as an option (with not observable) whenever pubis or ischium is present would be the most inclusive?

Does this help???

**Comment by 15E601** [comment]
That makes sense. I think this should work fine, though I will need to expand the entry forms so the module won't be implemented just yet. I will close the issue once the module is completed.
