### ISSUE TITLE
Dental inventory: Make molar wear scores aggregates of quadrant scores

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#69]
Sylvia Cheever reports the following bug:

**In what module does the bug occur?**
In the dental inventory all sections a bout quadrants of the dentition have a measurement datum on tooth wear for each tooth. Different value specifications apply, depending on the respective tooth type (incisors and canines, premolars, molars). This issue exclusively applies to the measurement data about molars.
 
**Describe the bug**
The wear scores for the adult molars represent the sum of the individual scores for each quadrant of the tooth, which are scored according to the dental inventory key for molars. As such, the verbal descriptors of the scores for the quadrants do not apply to the whole tooth, and do not accurately reflect the wear of the full tooth. [...] The current drop down descriptors do not reflect what is happening wear-wise on the full molar.

**Expected behavior**
[W]e do not actually record the individual scores for each quadrant, only the aggregate score of all four, so adding additional drop-down 'wear' sections for each quadrant of each molar would not work, as we don't know what each individual quadrant was scored, only the sum. We should have a numeric entry field for 'Wear' for all adult molars where data editors or observers can just type in the numeric aggregate score.

**Comment by cuboideum** [comment]
The measurement data about molars need to be replaced by others with a scalar value specification. The accepted value range is 0 (4x0) to 40 (4x10).

**Comment by cuboideum** [comment]
@zarquon42b: The required changes are made to the ontology (commit https://github.com/RDFBones/Phaleron-DentalInventory/commit/99185548ea8df3b6d9438f744adc7b898a4e6b19) and are also reflected in the Phaleron App Ontology (commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/3323449e1c6bf448084a3aeca150f7989b9718d1). They can now be implemented in AnthroGraph.

Please take a good look at the updated building plan (commit https://github.com/RDFBones/RDFBonesGraphics/commit/2756679fa1e7478431ea98d0bf2d8b7e0dea664f). The employed value specification has been newly added and never been used before.

**Comment by zarquon42b** [comment]
Addressed in https://github.com/AnthroGraph/PBP-App/pull/49

**Comment by zarquon42b** [comment]
The updates are now deployed on our anthrograph implementation.

**Comment by zarquon42b** [comment]
@sacheever : can you delete and recreate your dental inventories on anthrograph? This is necessary due to changes in the ontology fixing this issue.

**Comment by sacheever** [comment]
> @sacheever : can you delete and recreate your dental inventories on anthrograph? This is necessary due to changes in the ontology fixing this issue.

@zarquon42b Yes! I can delete them today and will recreate them once the bug is fixed. I cannot do it right at this moment (teaching in 20 minutes) but it will be done by 2pm Central Time (U.S.)!
