### ISSUE TITLE
Taphonomy

### ISSUE THREAD

**Issue by HannahLiedl** [RDFBones/RDFBonesPhaleron#7]
**Is your feature request related to a problem? Please describe.**
For taphonomic observations the type "erosion" is missing in the list.

**Describe the solution you'd like**
Can we add "erosion" to the list of taphonomic observations?

**Comment by 15E601** [comment]
I am adding the following taphonomic label:

**ID:**  phaleron-si:13-Erosion
**Label:**  Erosion
**Definition:**  The bone surface is damaged by erosion.

This means Erosion would equate to a hypothetical score of 13 in the Inventory Scoring Key. 

For the sake of understanding: I am having difficulty seeing how bones could experience erosion. In geological terms, I understand weathering to be the act of degradation of the rock surface, while erosion is the process of moving the ablation produced by weathering to another location. How does this translate to taphonomy?

**Comment by HannahLiedl** [comment]
Thank you!

We use the term erosion to describe loss/destruction of bone surface. It can be related to weathering. The definition is a bit different than in geological contexts.

**Comment by JEB13** [comment]
Agree with Hannah!

**Comment by 15E601** [comment]
Erosion has been added.
