### ISSUE TITLE
Development/Eruption Fields for Permanent Teeth (Part 2)

### ISSUE THREAD

**Issue by sacheever** [RDFBones/RDFBonesPhaleron#70]
**In what module does the bug occur?**
Dental Inventory (in Skeletal Inventory Module)
 
**Describe the bug**

It was mentioned in a previous ([issue 59](https://github.com/RDFBones/RDFBonesPhaleron/issues/59)), resolved issue that we needed to add the fields of development and eruption to adult teeth so that if we must score the teeth with respect to those fields, we are able to. The database was altered to accommodate. 

I agree with Hannah’s assessment that it should be **possible** to score adult teeth in the development and eruption categories in instances where we need to. The issue presently is that as the database currently stands it is **required** (because the fields have asterisks requiring a value be entered) to score in these categories to be able to ‘save’ any recording data for the maxillary and mandibular arcades at all. This is an issue because while some teeth do have scores for these fields, many do not, purposefully.

**To Reproduce**
If you open a Dental Inventory and you go to enter data into any of the ‘Permanent’ arcade sections, values are saved per arcade (right/left, maxillary/mandibular). There are drop down menus for each descriptive field for each tooth. If you enter in data from an adult set of dentition and do NOT provide a value for the ‘development’ or ‘eruption’ category (which have **not** been scored in the case of many of the adult teeth, though not all of the adult teeth), it will not allow you to save the data you have entered into the arcade section, because development and eruption fields are required to be completed. It will throw an error message saying that a value is required in the development and eruption fields, and none of the current options in the drop down menu for either are relevant to these instances where data was not collected (purposefully).

**Expected behavior**

Though we MAY have a score to enter in the development and eruption fields for adult teeth, a great many of our adult individuals do not have data for these fields. We need these fields to be an option for adult teeth, but not a requirement for adult teeth to accommodate the great many instances where we have no score for ‘development’ or ‘eruption’ for an adult tooth. 

There are two possible solutions that I can think of, but let me know if neither of these are viable:

1- An addition of an item in the drop down menu options (under development and eruption) for ‘No Data’ or ‘Intentionally Not Recorded’ if you intend to keep those fields as requiring a value in order to save. 

2- The requirement of entering a value for those fields in adult teeth in order to save your entered data could be lifted, making those ‘optional’ fields that are only filled out when applicable, such that it is possible to save data without entering a value in them

**Comment by cuboideum** [comment]
> 1- An addition of an item in the drop down menu options (under development and eruption) for ‘No Data’ or ‘Intentionally Not Recorded’ if you intend to keep those fields as requiring a value in order to save.

I would not consider this a good solution. The data entry form should work for all standard cases.

**Comment by cuboideum** [comment]
> 2- The requirement of entering a value for those fields in adult teeth in order to save your entered data could be lifted, making those ‘optional’ fields that are only filled out when applicable, such that it is possible to save data without entering a value in them

Technically, it is easy to make data fields optional, i.e. you can save the form without filling them in.

**Comment by sacheever** [comment]
> > 2- The requirement of entering a value for those fields in adult teeth in order to save your entered data could be lifted, making those ‘optional’ fields that are only filled out when applicable, such that it is possible to save data without entering a value in them
> 
> Technically, it is easy to make data fields optional, i.e. you can save the form without filling them in.

But the dental inventory sections are not set up so that you can save the data between individual traits per tooth. You fill out all the data for the whole arcade, and all of the fields are required before you can save. It will not let me save the arcade without filling those fields in. That is the issue. Perhaps that is a glitch of some kind?

**Comment by cuboideum** [comment]
The original issue was motivated by the need to enter mixed dentitions. I would guess that permanent teeth in such a dentition would be rated like this:

1. The deciduous tooth is still in the socket -> development: Unobservable, eruption: Not erupted
2. The permanent tooth is erupted but not yet fully developed -> development: some development stage, eruption: Partially erupted or Fully erupted
3. The permanent tooth is erupted and fully developed -> development: apex closed with normal PDL width (highest level), eruption: Fully erupted
4. The permanent tooth is lost -> development: Unobservable, eruption: Unobservable

Is this correct? What would be a scenario where none of the options applies?

**Comment by cuboideum** [comment]
@JEB13, @HannahLiedl, @hayesleigh and @jessica-rothwell, what do you think?

Note to @sacheever: People might only get notified of issues if they are mentioned.

**Comment by sacheever** [comment]
> The original issue was motivated by the need to enter mixed dentitions. I would guess that permanent teeth in such a dentition would be rated like this:
> 
> 1. The deciduous tooth is still in the socket -> development: Unobservable, eruption: Not erupted
> 2. The permanent tooth is erupted but not yet fully developed -> development: some development stage, eruption: Partially erupted or Fully erupted
> 3. The permanent tooth is erupted and fully developed -> development: apex closed with normal PDL width (highest level), eruption: Fully erupted
> 4. The permanent tooth is lost -> development: Unobservable, eruption: Unobservable
> 
> Is this correct? What would be a scenario where none of the options applies?

I am happy to complete dental inventories by fabricating/filling in that that data where it has not been provided in the excel sheets. As a secondary data editor, I did not want to generate new data values in fields that had been left blank by the original observer without consensus/approval, so was thinking more in terms of preserving the data as it was presented or recorded/not recorded by the original observer.

**Comment by HannahLiedl** [comment]
We had to add this in order to record developing permanent dentition. I'm recording development and eruption for all teeth now, but obviously this is missing in the earlier recordings and I'm also not sure if everyone has adopted this. The way it was intended in the orginial forms to just add it when necessary did not translate into the database. I'm a bit hesitant to say "Just recreate it" because it might be not as straight forward. While most of the permanent dentition would be fully developed and erupted (it should definitely be recorded if not!), it might be more difficult to differentiate between unobservable and observable. I tend to fit the teeth back into the sockets for photos even if they are lose and technically can be scored for development.
At this stage, it might be easiest to make it optional so Sylvia can actually enter the data. But I would be very careful with trying to recreate data without the dentition in front of you as there is a danger to add more mistakes into the recording and making it less traceable.

**Comment by sacheever** [comment]
> We had to add this in order to record developing permanent dentition. I'm recording development and eruption for all teeth now, but obviously this is missing in the earlier recordings and I'm also not sure if everyone has adopted this. The way it was intended in the orginial forms to just add it when necessary did not translate into the database. I'm a bit hesitant to say "Just recreate it" because it might be not as straight forward. While most of the permanent dentition would be fully developed and erupted (it should definitely be recorded if not!), it might be more difficult to differentiate between unobservable and observable. I tend to fit the teeth back into the sockets for photos even if they are lose and technically can be scored for development.
> At this stage, it might be easiest to make it optional so Sylvia can actually enter the data. But I would be very careful with trying to recreate data without the dentition in front of you as there is a danger to add more mistakes into the recording and making it less traceable.


@HannahLiedl I couldn’t agree more. As someone who is a secondary observer and who has never looked at a lot of these individuals, I felt that fabricating data that had not been provided by the primary observer, based on assumption only, is a slippery slope. Especially because there is some variation on what those values for development and eruption are going to be with respect to complete/unobservable, even in the case of a present and relatively complete adult tooth (ex: a root of a loose tooth could be damaged enough that you can’t observe whether the apex is actually closed, and assuming it was complete would be inaccurate). Jane has been very adamant that bad/inaccurate data shouldn’t be in the database and I’m inclined to say that entering data a secondary observer is making up on inference or assumption isn’t the most responsible data practice.

**Comment by cuboideum** [comment]
In order not to mislead analyses, you should strive to achieve similar detail and accuracy for all individuals. Would it be feasible to go back to the material to check the cases in question?

We need your decision here.

**Comment by HannahLiedl** [comment]
It is a large amount of individuals who have this information not present as we only introduced this fairly recently. I don't have the time now to go back and double check on all of them. If we agree that all of them need this level of detail, maybe Elizabeth can go back when she comes to Athens in the fall. Otherwise, I think the option to make filling out the dental development optional should be seriously considered. These fields are recorded for the individuals where it is actually necessary for age-at-death. Obviously adults will have fully developed incisors, but going back to 150+ individuals to make sure all of this is filled out as either developed or unobservable is extremely time consuming and I'm not sure the time spent on this is would be well-spent when there are so many more individuals to record.

**Comment by cuboideum** [comment]
During a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph work group on 9 August 2022 it was decided that data input for development and eruption scores in controls about teeth other than M3 should be made optional. Data entry for M3 shall remain compulsory.

The optional fields shall be completed for all mixed dentitions but remain empty for permanent dentitions.

**Comment by cuboideum** [comment]
@zarquon42b: This implies the following changes in AnthroGraph:

In the skeletal inventory sections 'Permanent maxillary dentition' (phaleron-di:PermanentMaxillaryDentition) the following controls need to be made optional:

* Measurement datum 'Development of tooth' (phaleron-di/DevelopmentOfTooth) about
   * 'Entire left second upper molar tooth' (rdfbones:EntireTooth_fma55700)
   * 'Entire left first upper molar tooth' (rdfbones:EntireTooth_fma55699)
   * 'Entire left second upper premolar tooth' (rdfbones:EntireTooth_fma55691)
   * 'Entire left first upper premolar tooth' (rdfbones:EntireTooth_fma55690)
   * 'Entire left upper canine tooth' (rdfbones:EntireTooth_fma55799)
   * 'Entire left upper lateral incisor tooth' (rdfbonesEntireTooth_fma55683)
   * 'Entire left upper central incisor tooth' (rdfbones:EntireTooth_fma55682)
   * 'Entire right upper central incisor tooth' (rdfbones:EntireTooth_fma55681)
   * 'Entire right upper lateral incisor tooth' (rdfbones:EntireTooth_fma55680)
   * 'Entire right upper canine tooth' (rdfbones:EntireTooth_fma55798)
   * 'Entire right first upper premolar tooth' (rdfbones:EntireTooth_fma55689)
   * 'Entire right second upper premolar tooth' (rdfbones:EntireTooth_fma55688)
   * 'Entire right first upper molar tooth' (rdfbones:EntireTooth_fma55698)
   * 'Entire right second upper molar tooth' (rdfbones:EntireTooth_fma55697)
* Measurement datum 'Eruption of tooth' (phaleron-di:EruptionOfTooth) about
   * 'Secondary left second upper molar tooth position' (rdfbones:SecondaryLeftSecondUpperMolarToothPosition)
   * 'Secondaryleft first upper molar tooth position' (rdfbones:SecondaryLeftFirstUpperMolarToothPosition)
   * 'Secondary left second upper premolar tooth position' (rdfbones:SecondaryLeftSecondUpperPremolarToothPosition)
   * 'Secondary left first upper premolar tooth position' (rdfbones:SecondaryLeftFirstUpperPremolarToothPosition)
   * 'Secondary left upper canine tooth position' (rdfbones:SecondaryLeftUpperCanineToothPosition)
   * 'Secondary left upper lateral incisor tooth position' (rdfbones:SecondaryLeftUpperLateralIncisorToothPosition)
   * 'Secondary left upper central incisor tooth position' (rdfbones:SecondaryLeftUpperCentralIncisorToothPosition)
   * 'Secondary right upper central incisor tooth position' (rdfbones:SecondaryRightUpperCentralIncisorToothPosition)
   * 'Secondary right upper lateral incisor tooth position' (rdfbones:SecondaryRightUpperLateralIncisorToothPosition)
   * 'Secondary right upper canine tooth position' (rdfbones:SecondaryRightUpperCanineToothPosition)
   * 'Secondary right first upper premolar tooth position' (rdfbones:SecondaryRightFirstUpperPremolarToothPosition)
   * 'Secondary right second upper premolar tooth position' (rdfbones:SecondaryLeftSecondUpperPremolarToothPosition)
   * 'Secondary right first upper molar tooth position' (rdfbones:SecondaryRightFirstUpperMolarToothPosition)
   * 'Secondary right second upper molar tooth position' (rdfbones:SecondaryLeftSecondUpperMolarToothPosition)

In the skeletal inventory sections 'Permanent mandibular dentition' (phaleron-di:PermanentMandibularDentition) the following controls need to be made optional:

* Measurement datum 'Development of tooth' (phaleron-di/DevelopmentOfTooth) about
   * 'Entire left second lower molar tooth' (rdfbones:EntireTooth_fma55703)
   * 'Entire left first lower molar tooth' (rdfbones:EntireTooth_fma55704)
   * 'Entire left second lower premolar tooth' (rdfbones:EntireTooth_fma55692)
   * 'Entire left first lower premolar tooth' (rdfbones:EntireTooth_fma55693)
   * 'Entire left lower canine tooth' (rdfbones:EntireTooth_fma55687)
   * 'Entire left lower lateral incisor tooth' (rdfbones:EntireTooth_fma57141)
   * 'Entire left lower central incisor tooth' (rdfbones:EntireTooth_fma57143)
   * 'Entire right lower central incisor tooth' (rdfbones:EntireTooth_fma57142)
   * 'Entire right lower lateral incisor tooth' (rdfbones:EntireTooth_fma57140)
   * 'Entire right lower canine tooth' (rdfbones:EntireTooth_fma55686)
   * 'Entire right first lower premolar tooth' (rdfbones:EntireTooth_fma55694)
   * 'Entire right second lower premolar tooth' (rdfbones:EntireTooth_fma55695)
   * 'Entire right first lower molar tooth' (rdfbones:EntireTooth_fma55705)
   * 'Entire right second lower molar tooth' (rdfbones:EntireTooth_fma55706)
* Measurement datum 'Eruption of tooth' (phaleron-di:EruptionOfTooth) about
   * 'Secondary left second lower molar tooth position' (rdfbones:SecondaryLeftSecondLowerMolarToothPosition)
   * 'Secondaryleft first lower molar tooth position' (rdfbones:SecondaryLeftFirstLowerMolarToothPosition)
   * 'Secondary left second lower premolar tooth position' (rdfbones:SecondaryLeftSecondLowerPremolarToothPosition)
   * 'Secondary left first lower premolar tooth position' (rdfbones:SecondaryLeftFirstLowerPremolarToothPosition)
   * 'Secondary left lower canine tooth position' (rdfbones:SecondaryLeftLowerCanineToothPosition)
   * 'Secondary left lower lateral incisor tooth position' (rdfbones:SecondaryLeftLowerLateralIncisorToothPosition)
   * 'Secondary left lower central incisor tooth position' (rdfbones:SecondaryLeftLowerCentralIncisorToothPosition)
   * 'Secondary right lower central incisor tooth position' (rdfbones:SecondaryRightLowerCentralIncisorToothPosition)
   * 'Secondary right lower lateral incisor tooth position' (rdfbones:SecondaryRightLowerLateralIncisorToothPosition)
   * 'Secondary right lower canine tooth position' (rdfbones:SecondaryRightLowerCanineToothPosition)
   * 'Secondary right first lower premolar tooth position' (rdfbones:SecondaryRightFirstLowerPremolarToothPosition)
   * 'Secondary right second lower premolar tooth position' (rdfbones:SecondaryRightSecondLowerPremolarToothPosition)
   * 'Secondary right first lower molar tooth position' (rdfbones:SecondaryRightFirstLowerMolarToothPosition)
   * 'Secondary right second lower molar tooth position' (rdfbones:SecondaryRightSecondLowerMolarToothPosition)

**Comment by cuboideum** [comment]
The required changes are implemented and the AnthroGraph production instance has been updated.
