### ISSUE TITLE
Wear Score Dropdown Order

### ISSUE THREAD

**Issue by jstamer95** [RDFBones/RDFBonesPhaleron#71]
**In what module does the bug occur?**
Dental Inventory
 
**Describe the bug**

For the majority of the drop down lists, the order follows the numerical option that we have been using in data collection. In the case of dental wear, the options follow the 0-10 severity scale, from "no information available" to "no enamel..." However, in the adult mandibular and maxillary dropdowns for both the "molar" and "canine/incisor" tooth type, score "Quadrant area is worn flat (horizontal) but there is no dentine exposure" comes first and is out of place, and score "Large dentin area with enamel rim complete" comes first and is out of place in these tooth types respectively. 

Keeping the order consistent with the severity or numerical counterparts will help improve useability and reduce user confusion and the potential to input errors.

**To Reproduce**
1. Go to '...' "perm. maxilla"
2. Click on '....' either "wear M3" or "wear C" 
3. notice the order of the drop down menu 

**Expected behavior**

"Quadrant area is worn flat..." should come between: "Any cusp in the quadrant area is rounded" and "dentine exposure one-fourth of quadrant or less."

"Large dentine area..." should come between: "Moderate dentin exposure no longer resembling a line" and Large dentin area with enamel rim lost on one side or very tiny enamel only"

**Comment by cuboideum** [comment]
Well observed. The bug is already known and there is [another (internal) issue](https://github.com/RDFBones/RDFBones-O/issues/159) dealing with it. Closing that issue should also close this one.

**Comment by cuboideum** [comment]
Closed via issue https://github.com/RDFBones/RDFBones-O/issues/159.
