### ISSUE TITLE
Paleopathology of the Shoulder Girdle - Missing ROIs

### ISSUE THREAD

**Issue by sacheever** [RDFBones/RDFBonesPhaleron#72]
**In what module does the bug occur?**
Paleopathology
 
**Describe the bug**
When you go to the 'Shoulder Girdle' tab and go to enter any type of paleopathology, the only ROI available in the drop down menu to select is 'left clavicle body'. In one instance (Osteoarthritis/Osteoporosis), there are no ROIs available.

**To Reproduce**
1. Enter into the paleopathology entry of any individual
2. Go to the 'Shoulder Girdle' tab and begin a new entry for any type of pathology
3. Click on the ROI dropdown menu to specify where the pathology occurs
4. See error - Either only 'left clavicle body' is available or the dropdown list says 'no options available'

**Expected behavior**
When you click the ROI dropdown list all of the elements included in the shoulder girdle should be there. This includes for R and L: Scapula bodies, glenoid fossae, clavicular articulations, clavicle bodies, medial and scapular articulations of clavicle,

**Comment by cuboideum** [comment]
The pathology module only offers those ROIs that are coded 'observable' in the related skeletal inventory. Please check if this is the case for the ROI you expect to find in the drop-down list.

**Comment by sacheever** [comment]
Yes! Apologies, I did not do the skeletal inventory for the individual in question and it appears someone erroneously coded an element as 'unobservable' that was actually observable and had pathology associated with it. I have the corrected the error on this end and everything is in order. Thank you!
