### ISSUE TITLE
No option to input person involved/creator for inventories

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#74]
When creating a skeletal inventory there is no longer the option to input the name of the observer or person involved. There is only the role type and the date. There should be an option to have a name associated with each role type or editing event. The table at the bottom of the page has a column for person involved but there is no where for that data to be inputted. 

![image](https://user-images.githubusercontent.com/90316213/185652656-e9c23420-3944-4210-ac5a-73d52fc74656.png)

**Comment by 15E601** [comment]
This is a two-step process. First you create an entry in the table at the bottom of the page (as you have done in your screenshot). You now have an entry for "2022-06-17". In the column "Observer/Editing Event", click the blue "Observer ->" link in the row, and it will take you to a new page on a new browser tab where you can enter the name. Once you save the name, you can close the tab and continue as usual.

**Comment by cuboideum** [comment]
@zarquon42b: Please add instructions to interface.

**Comment by zarquon42b** [comment]
Fixed in https://github.com/AnthroGraph/RDFBones-App/commit/9742465d760822a0f3956f8f382e6003abe37db3
