### ISSUE TITLE
Dental Inventory Comment Box

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#75]
Hi all,

I was wondering if it would be possible to add a comment/notes section to the general tab of the dental inventory module, similar to the notes section in the skeletal inventory module (pictured below).

![image](https://user-images.githubusercontent.com/90316213/195407045-6e099981-5f83-4b5e-9e96-84ec81f30672.png)

**Comment by cuboideum** [comment]
At a meeting of the Phaleron Bioarchaeological Project with the RDFBones/AnthroGraph workgroup on 18 October 2022 this issue got the 'go ahead' for implementation in AnthroGraph.

**Comment by zarquon42b** [comment]
Fixed in [accdf52](https://github.com/AnthroGraph/PBP-App/commit/9fdda1314f29ac1437f02e87fd763e8b0681c203)
And already deployed on reference machine.
