### ISSUE TITLE
No option to put multiple ‘aspects’/‘locations’ for OA/OP lesions in Paleopath modules

### ISSUE THREAD

**Issue by sacheever** [RDFBones/RDFBonesPhaleron#76]
**In what module does the bug occur?**
Skeletal Paleopathology
 
**Describe the bug**
When entering an OA/OP lesion, after selecting an ROI, the first field under ‘Additional Information’ is: “ Location Of Osteoarthritis Or Osteoporosis Lesion”, which has the standard ‘aspect’ descriptors such as anterior, posterior, medial, lateral, etc. as options in the drop down menu. As with other types of pathology, there is potential to need to list multiple ‘aspects’/‘locations’ for the pathology if the lesion crosses multiple surfaces (for example, if lipping of the proximal epiphysis impacted the anterior AND medial edges of the articular surface). However, you are only able to enter a single location/aspect with no option to add another. 

**To Reproduce**
1. Go to any individual and portion of the body
2. Click on ‘Create New OA/OP entry’
3. Scroll down to Additional Information
4. Click on “ Location Of Osteoarthritis Or Osteoporosis Lesion”5. 
5. See error - only one ‘location’/‘aspect’ may be selected.

**Expected behavior**

There should be an option to ‘add additional Location of Osteoarthrtitis or Osteoporosis’

**Comment by sacheever** [comment]
@JEB13, @HannahLiedl, @hayesleigh, @jstamer95, @jessica-rothwell

**Comment by HannahLiedl** [comment]
I agree with Sylvia: it is also necessary for OA to be able to enter multiple aspects affected just we have it with the other pathologies.

**Comment by zarquon42b** [comment]
Hi everyone, 
from my side (implementation point of view), this is no big thing and I can change this easily. Please discuss this among yourselves and communicate the final verdict ;)

**Comment by jstamer95** [comment]
I agree; great comment Sylvia!

**Comment by cuboideum** [comment]
At the meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 21 October 2022 we agreed that the control should take multiple entries.

**Comment by zarquon42b** [comment]
Fixed in https://github.com/AnthroGraph/PBP-App/commit/1546b231b320420144ccc764f805697f47257390
