### ISSUE TITLE
‘Bone Loss Structure’ and ‘Abnormal Matrix: Presence/Absence’ Scoring Confusion

### ISSUE THREAD

**Issue by sacheever** [RDFBones/RDFBonesPhaleron#78]
**In what module does the bug occur?**

Skeletal Paleopathology
 
**Describe the bug**

This is either a bug or a data collection issue, depending on how we decide to solve it:

For ‘Bone Loss Structure’ there are only options of 1-4, but in the case of a focal lesion, some original observers have put a ‘9’ in the excel spreadsheets (which is not listed as an option in the protocols) – we either need to add in a ‘9’ (unobservable) option for this category or we need to decide which of the categories (1-4) should be scored for a focal lesion so data editors can replace the ‘9’s with one of the available options. (I imagine the issue is arising from the fact that all options for Bone Loss Structure refer to porosity, which isn’t exactly what is observable when you just have a single focal lesion)?

The same issue also occurs with ‘Abnormal Matrix Presence/Absence’ in the Bone Addition instance - the only options are 0/1 (Absent/Present), but people are putting ‘9’s. The ‘Abnormal Matrix’ Scoring category is not mentioned in the Paleopathology scoring protocols at all, which might explain observer confusion on how they should be scoring. 

**To Reproduce**
Go into Skeletal Paleopathology and create a ‘Bone Loss’ instance - for ‘Bone Loss Structure’ Category there is no ‘Unobservable/Indeterminate’ option. 

Go to Skeletal Paleopathology and create a ‘Bone Addition’ Instance - for the ‘Abnormal Matrix’ Category the drop down only has an ‘Absent’ option and a ‘Present’ option

**Expected behavior**
Inclusion of the ‘9’/Unobservable score in the Bone Loss Structure category and the ‘Abnormal Matrix’ Category

OR

A halt on observers using ‘9’ for this category in the case of focal lesions and in the ‘Abnormal Matrix’ category for Bone Addition. In addition a consensus amongst us about what value data editors should replace existing ‘9’s in these categories with for the database. I am happy to do the replacement, I just don’t want to make any executive decisions on what we should replace the ‘9’s with sans consultation with all of the project bioarchaeologists.

**Screenshots**

![E1AD1F2F-69EF-4315-A05B-28C2D9E17BBB](https://user-images.githubusercontent.com/99766396/202827194-39369f61-18e9-4e03-907c-b9f0572aac49.jpeg)
![65C9EE3C-766C-4086-8801-C4B0946B988E](https://user-images.githubusercontent.com/99766396/202827195-c492438f-c56e-4721-b92f-6baea4ac7017.jpeg)
![BA5A2AA2-45F2-4DBD-AC4B-ACAFB4C028D4](https://user-images.githubusercontent.com/99766396/202827196-8e98974b-9809-4101-ada4-f4e2260b4ac2.jpeg)

**Comment by sacheever** [comment]
@JEB13, @HannahLiedl, @hayesleigh, @jstamer95, @jessica-rothwell

**Comment by cuboideum** [comment]
Elizabeth has updated the Scoring key. We are ready for implementation in the ontology extension.

**Comment by cuboideum** [comment]
Added required changes to [network graphic](https://github.com/RDFBones/RDFBonesGraphics/compare/main...BoneLossStructure#diff-53a42eb2a22b534042dbf87fc708679c858bace2f502a533e369d0ec04c79426) with commit https://github.com/RDFBones/RDFBonesGraphics/commit/c0a0ace2071ecee7e42dab710a52bb2c2b282bb9.

**Comment by cuboideum** [comment]
The requested changes are implemented in the Phaleron-Pathologies ontology extension and in the AnthroGraph software application.
