### ISSUE TITLE
Dental pathology required data error

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#79]
Within the dental pathology module the location of calculus fields are marked as required. However, they should be optional. As far as I can tell it is only the mandibular left incisors. 

![image](https://user-images.githubusercontent.com/90316213/205996545-43449065-bd2d-4c46-99c8-27090d96aca7.png)

 
As seen in the photo for the left lateral incisor (I2) the presence of calculus is marked unobservable, but I am forced to input a calculus location. 

To fix this issue all of the locations of calculus fields should be optional to input.

**Comment by cuboideum** [comment]
pahleron-dpatho:LocationOfCalculus is only to be completed if phaleron-dpatho:PresenceOfCalculus is not rated as either 'absent' or 'unobservable'. So I would also say that the item should be optional.

**Comment by cuboideum** [comment]
@zarquon42b: Could you please make all 'Location of Calculus' items optional?

**Comment by zarquon42b** [comment]
I don't know what you are referring to? In anthrograph all those items are optional.

**Comment by zarquon42b** [comment]
@hayesleigh can you please check again.

**Comment by hayesleigh** [comment]
![image](https://user-images.githubusercontent.com/90316213/207889692-cafe4f3b-ed09-4529-8f46-9f6038afc0f3.png)

I have double-checked and these two fields are still saying that they are required fields. It will not let me save the left side of the permanent mandibular dentition without inputting a value in these two fields. Which is an issue due to the absence of calculus. 

![image](https://user-images.githubusercontent.com/90316213/207890482-4573c66e-9ffa-424e-894c-e83a6ad8d050.png)

**Comment by zarquon42b** [comment]
Fixed.
