### ISSUE TITLE
Scoring ribs, hand and foot bones by side rather than by bone

### ISSUE THREAD

**Issue by JEB13** [RDFBones/RDFBonesPhaleron#8]
It slows us down to score by individual bones, though once the bug requiring saving by line is fixed, this may be less of a problem

Organize the template so that all left ribs/right ribs, left carpals/right carpals, left metacarpals/right metacarpals, left tarsals/right tarsals, left metatarsals/right metatarsals are scored in sequence.

**Comment by zarquon42b** [comment]
> bug requiring saving by line is fixed, this may be less of a problem

That is not the actual bug. The bug is that we need to reload the page before changing the values. 
The ROI-wise saving allows you to leave before recording all bones otherwise, you would need to fill the entire section before saving.
Are you proposing a global Save button for each section?

**Comment by JEB13** [comment]
No, I am not.  This, then seems to be working, but re-ordering the entries would expedite, as per this "issue."

**Comment by JEB13** [comment]
OOPS, wrong button

**Comment by 15E601** [comment]
I have updated the Ribs, the Arm section, the Leg section, and the Carpals. I have removed all other Ribs to reduce confusion, and have not updated the Metacarpals and Tarsals.

**The time investment for this UI change is very large, so please tell me if this is acceptable.**

I will then change the rest as well. You can log onto AnthroGraph and interact with the inventories to get a better feel for it, everything should work as before, just with a different in UI.

![ribs](https://user-images.githubusercontent.com/67172847/133622893-83763db3-cce0-49b7-8107-af8d5cfe2eb5.png)

![carpals](https://user-images.githubusercontent.com/67172847/133622091-bddbe4f3-6b3f-4cb9-8685-b0da889dca31.png)

**Comment by JEB13** [comment]
This looks good, down to unaided fragments of specific carpals.  How often do we have such data and how useful.  I would think grouping carpals together would work.

**Comment by 15E601** [comment]
Then I will delete all fields for unsided fragments of specific carpals, and you will be left only with the 3 fields of "Carpals, grouped". The exact same will apply to specific tarsals.
As per #11, I will also separate the neural arches from the vertebral bodies. I would make it so you first enter all left neural arches, then all right neural arches, then all bodies.

**Comment by 15E601** [comment]
Likewise, I will remove unsided fragments of specific metacarpals and metatarsals

**Comment by 15E601** [comment]
All split by side.
