### ISSUE TITLE
[Phaleron-Pathologies]: Skull ROI to be referenced by 'is about' axioms

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#80]
In the 'Size and Shape' section of the paleopathology module, data items relating to abnormal size and shape of the skull need to be about an anatomical region of interest representing the skull as a whole. This was decided during a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 22 November 2022.

In the RDFBones core ontology, there is the ROI rdfbones:EntireSetOfBonesOfSkull which we have already used in the Phaleron skeletal inventory for counts of skull fragments. While this is a good reference to indicate that a measurement datum is about the skull, it is not linked to ROIs referencing bones or part of bones of the skull that are scored for the Phaleron skeeltal inventory.

For the 'Size and Shape' section I see the following options for implementation in the ontology extension:

1. We use rdfbones:EntireSetOfBonesOfSkull. As a consequence, an internal validation if rating of abnormal size and shape of the skull is feasible given entries in the skeletal inventory is impossible.
2. We create a new ROI representing the skull which is a combination of all skull segments that are scored in the Phaleron skeltal inventory. Here, the creation of a skull size and shape dataset section can be tied to the precondition that at least some of the skull segments have been scored as observable.

@zarquon42b: Which solution do you prefer?

**Comment by cuboideum** [comment]
Sorry, I completely forgot about our phaleron-app:PhaleronSkullROIGroup. So we could use that for evaluation if required and still make the database section about rdfbones:EntireSetOfBonesOfSkull. @zarquon42b: What do you think?

**Comment by cuboideum** [comment]
This issue was discussed during a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 13 December 2022.

Evaluation of skeletal inventories needs to be based on ratings of 'presence' rather than of 'observability'. 'Observability' refers to the bone surface while overall shape does not depend on surface preservation.

@JEB13 and Elizabeth will figure out what anatomical regions of the skull from the skeletal inventory should be required to prevent a skull from being classified as 'unobservable'.

**Comment by elizabethhannigan** [comment]
@cuboideum Jane and I discussed and think option #2 is best for the skull. But maybe we should discuss with others at the next meeting. We think the frontal bone and at least 1 parietal bone would need to be present to say the skull to be observable.

**Comment by cuboideum** [comment]
During a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 17 January 2023 the [solution](https://github.com/RDFBones/RDFBonesPhaleron/issues/80#issuecomment-1359150654) suggested by @elizabethhannigan was accepted.

This can now be implemented.

**Comment by cuboideum** [comment]
Fixed with https://github.com/RDFBones/Phaleron-Pathologies/pull/8.
