### ISSUE TITLE
[Phaleron-Pathologies]: Long bone ROIs to be referenced by 'is about' axioms

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#81]
Analogous to https://github.com/RDFBones/RDFBonesPhaleron/issues/80, should we use the ROIs of type 'Entire bone organ' form the RDFBones core ontology for the 'Size and Shape' section about long bones? Or should we define new ROIs as combinations of the Phaleron ROIs representing segments of long bones?

The latter solution would allow for evaluation of data entries from the skeletal inventory.

ROI groups are of no help, here.

@zarquon42b: What do you think?

**Comment by cuboideum** [comment]
This issue was discussed during a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 13 December 2022.

Evaluation of skeletal inventories needs to be based on ratings of 'presence' rather than of 'observability'. 'Observability' refers to the bone surface while overall shape does not depend on surface preservation.

@JEB13 and Elizabeth will figure out what anatomical regions of long bones from the skeletal inventory should be required to prevent long bones from being classified as 'unobservable'.

**Comment by elizabethhannigan** [comment]
@cuboideum Okay Jane and I think that we should use the existing ROIs for long bone change in shape. And if any third of the diaphysis (distal, middle, or proximal) is present, that is enough to say observable. If no thirds of the diaphysis are present, then this would be unobservable.

**Comment by cuboideum** [comment]
During a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup the [solution](https://github.com/RDFBones/RDFBonesPhaleron/issues/81#issuecomment-1359155538) suggested by @elizabethhannigan was accepted.

It can now be implemented in the ontology extension.

**Comment by cuboideum** [comment]
@JEB13, @HannahLiedl and @elizabethhannigan, do you occasionally rate metacarpals, metatarsals and phalanges for size and shape abnormalities or just the long bones of the arm and the leg? What about clavicles?

**Comment by cuboideum** [comment]
Fixed with https://github.com/RDFBones/Phaleron-Pathologies/pull/8.
