### ISSUE TITLE
Paleopathology Template: Remove Items From Vertebral Form and Size Section

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#82]
**In what module does the bug occur?**
'Size and Shape' - 'Vertebral' columns of the Phaleron paelopathology template, version of 16 March 2022, last inspected on 08 December 2022.
 
**Describe the bug**
In a meeting between the Phaleorn Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 22 November 2022 it was decided to drop the data item 'Ankylosis: Presence' from the section on abnormal size and shape of vertebrae because ankylosis is already scored with vertebral pathologies. During the meeting, it was also debated what the data item 'Form' in the same section was actually supposed to contain. @JEB13 consulted with @HannahLiedl and later communicated via email that both of them thought that the item could be dropped.

**Expected behavior**
Please update the Phaleron Paleopathology Template by removing the columns 'Form' and 'Ankylosis: Presence' from the Size and Shape - Vertebral section.

**Comment by HannahLiedl** [comment]
I'm sorry this took a while, but I got rid of the vertebral column section in the "size and shape" section both in the recording template and in the scoring key. The updated template and scoring key are marked with today's date (19th December).
