### ISSUE TITLE
Label for Decid. Mandibular Arcade is Inaccurate

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#85]
Within the dental pathology module the Decid Mandibular dentition labels all say maxillary arcade instead of mandibular. 

The labels should read Right Mandibular Arcade and the save buttons should read Save Right Mandibular Arcade, etc. 
 
![image](https://user-images.githubusercontent.com/90316213/208467449-d48c0642-2568-4827-abdf-8074424fe67a.png)

**Comment by zarquon42b** [comment]
Fixed in https://github.com/AnthroGraph/PBP-App/commit/764b8b9c400fa879144e657ed59b9c448198a216
