### ISSUE TITLE
Multiple Carious lesions in the same surface 

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#86]
**In what module does the bug occur?**
Within the dental pathology module when there are multiple carious lesions they can not occur on the same surface.

For example, individual IV_620 has two carious lesions on the occlusal surface. The database only allows for the occlusal surface label to be inputted once. This is an issue when it comes to researchers looking for the number of carious lesions. If we can't input a surface more than once there is currently no way to tell how many carious lesions occur on a single surface. 
 
![image](https://user-images.githubusercontent.com/90316213/208965466-356ecfda-7ad5-4afc-8c60-9b1074b5c461.png)

Ideally, the database would allow the same caries label to be inputted multiple times. Maybe we should discuss in our next meeting,

**Comment by 15E601** [comment]
This issue was discussed during the meeting on Jan 17. Allowing only one label per type to be added is an intended function. It was requested that a comment entry form be added to each of the four pathology tabs to allow such information as the number of carious lesions on the same surface to be recorded.

**Comment by cuboideum** [comment]
@zarquon42b: Can you implement 'comments' fields for the following classes?

* Dental pathology of deciduous mandibular arcade (phaleron-dpatho:DentalPaleopathologyDeciduousMandibularArcade)
* Dental pathology of deciduous maxillary arcade (phaleron-dpatho:DentalPaleopathologyDeciduousMaxillaryArcade)
* Dental pathology of permanent mandibular arcade (phaleron-dpatho:DentalPaleopathologyPermanentMandibularArcade)
* Dental pathology of permanent maxillary arcade (phaleron-dpatho:DentalPaleopathologyPermanentMaxillaryArcade)

**Comment by cuboideum** [comment]
@cuboideum and @hayesleigh discussed this issue in a video conference on 10 August 2023. It was decided that the comment boxes for individual tabs were not actually needed and that the issue should be closed.
