### ISSUE TITLE
ROI_ no options within mixed category of leg/foot

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#87]
Within the paleopathology module, there is a bug or I'm doing something wrong (unsure which) 

In individual IV_597's paleopathology data, I try to enter a mixed bone loss/formation entry within the leg/foot section. When I go to input the ROI-it reads "no options".

I double-checked the skeletal inventory and there should be ROIs available as they are marked observable. I'm not sure what is causing this issue. 

![image](https://user-images.githubusercontent.com/90316213/214088455-e948073d-ec45-4d2a-a20b-6adae7950220.png)

**Comment by 15E601** [comment]
In the **PhaleronPaleopathologyDataset** template, the class `http://w3id.org/rdfbones/anthrograph/app/phaleron-app/PhaleronLowerLimbArticularROIs`
is incorrectly used multiple times for the ROI type. It should instead be `http://w3id.org/rdfbones/anthrograph/app/phaleron-app/PhaleronLowerLimbROIs`

**Comment by zarquon42b** [comment]
Hi @hayesleigh ,
thanks for the valuable input. While looking in to this issue, we found another one (regarding postcranial parts) that has to be taken care of. Can you please not enter data in the mixed bone loss/formation form (except for the skull) until I have fixed this issue?

**Comment by hayesleigh** [comment]
Of course, I will hold off on entering that data until resolved.

**Comment by zarquon42b** [comment]
Hi everyone, 
the issues have been resolved and the changes applied to the anthrograph instance. Please test @hayesleigh .
Have a nice weekend!
