### ISSUE TITLE
Bone addition-abnormal matrix unobservable option

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#92]
**In what module does the bug occur?**
Skeletal pathology module-bone addition section
 
**Describe the bug**
Within the bone addition section, the scoring key shows an unobservable option for 'presence of abnormal matrix' that is currently not available in the database. 

**To Reproduce**
1. Go to osteo pathology individual. 
2. Click on bone addition. 
3. Scroll down to abnormal matrix
4. See no unobservable option. 

**Expected behavior**
Expect all abnormal matrix options including unobservable to be available. 

**Screenshots**
![image](https://user-images.githubusercontent.com/90316213/231798550-e00dcc97-da9e-4b59-b681-8f189f1b9233.png)
![image](https://user-images.githubusercontent.com/90316213/231799189-5ced39a5-729b-4546-ac57-bee1db57fec4.png)

**Additional context**

**Comment by cuboideum** [comment]
@zarquon42b: Pull request https://github.com/RDFBones/Phaleron-Pathologies/pull/17 changes the value specification for measurement 'Presence of abnormal matrix'. Commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/2b6b8446a16710a1c290e778e06a5958883c166d brings this to the Phaleron-AppOntology.

I assume that it suffices to load the new version of the app ontology into AnthroGraph without any further changes to AnthroGraph itself. Is this correct?

Please update AnthroGraph and/or do whatever is necessary to effect the desired change.

**Comment by zarquon42b** [comment]
Yep. Updating should suffice. I'm on it.

**Comment by cuboideum** [comment]
In a discussion between @zarquon42b and @cuboideum on 17 August 2023 it was ascertained that the information which value specifications measurement data in skeletal inventories have is hard-coded in the form controls of AnthroGraph. Therefore, changes to the app code are necessary.

Also, for existing data entries, current instances of value specifications need to be replaced by ones of the new value specification type.

Measurement datum: phaleron-patho:PresenceOfAbnormalMatrix ('Presence of abnormal matrix')
Old value specification: standards-patho:PresenceOfFeatureValueSpecification ('Presence of feature value specification')
New value specification: phaleron-patho:PresenceAndObservabilityOfFeatureValueSpecification ('Presence and observability of feature value specification')

**Comment by zarquon42b** [comment]
Here is the solution to change the VS class:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX phaleron-di: <http://w3id.org/rdfbones/ext/phaleron-di/>
PREFIX phaleron-dpatho: <http://w3id.org/rdfbones/ext/phaleron-dpatho/>
PREFIX standards-patho: <http://w3id.org/rdfbones/ext/standards-patho/>
PREFIX phaleron-patho: <http://w3id.org/rdfbones/ext/phaleron-patho/>

DELETE {
  ?svs a  standards-patho:PresenceOfFeatureValueSpecification .
}

INSERT { GRAPH ?g {
  ?svs a phaleron-patho:PresenceAndObservabilityOfFeatureValueSpecification .
  }
}
WHERE 
{
  GRAPH ?g {?s a phaleron-patho:PresenceOfAbnormalMatrix.}
  ?s a phaleron-patho:PresenceOfAbnormalMatrix.
  ?s <http://purl.obolibrary.org/obo/OBI_0001938> ?svs.
  ?svs a  standards-patho:PresenceOfFeatureValueSpecification .
  ?svs <http://purl.obolibrary.org/obo/OBI_0000999> ?o.
}
```

**Comment by zarquon42b** [comment]
Also updated production instance and knowledge graph.
