### ISSUE TITLE
Dental Pathology: Comments box for investigations

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#94]
**Is your feature request related to a problem? Please describe.**
Phaleron researchers have miscellaneous information related to investigations of dental pathologies. Currently, there is no data field to record these comments.

**Describe the solution you'd like**
There should be a text box for the entire investigation, analogous to the comment box for dental inventories (cf. #75).

**Additional context**
This issue was discussed during the meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 6 June 2023. It was originally raised by @hayesleigh.

**Comment by zarquon42b** [comment]
Fixed [here](https://github.com/AnthroGraph/PBP-App/commit/2418d68ce25fdb1ab28ec0a93192824afb564e28).
