### ISSUE TITLE
Possibly/possible in the sex estimation module

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#96]
Within the sex estimation module it currently offers possibly male and possibly female as options.
Could this be changed to read possible male and possible female as this is the wording the project uses?

**Comment by 15E601** [comment]
Fixed with [commit dd02172](https://github.com/RDFBones/Phaleron-SexEstimation/commit/dd021722d5ba5b3165838764a93a6dd37807accc)
